MLIR: mlir::StorageUniquer::BaseStorage Class Reference
mlir::StorageUniquer::BaseStorage Class Reference
This class acts as the base storage that all storage classes must derived from.
#include "mlir/Support/StorageUniquer.h"
Public Member Functions
unsigned getKind () const
Get the kind classification of this storage.
Protected Member Functions
BaseStorage ()
Detailed Description
This class acts as the base storage that all storage classes must derived from.
Definition at line 73 of file StorageUniquer.h.
Constructor & Destructor Documentation
BaseStorage()
mlir::StorageUniquer::BaseStorage::BaseStorage () inline protected
Definition at line 79 of file StorageUniquer.h.
Member Function Documentation
getKind()
unsigned mlir::StorageUniquer::BaseStorage::getKind () const inline
Get the kind classification of this storage.
Definition at line 76 of file StorageUniquer.h.
Referenced by mlir::ElementsAttr::getValue(), mlir::detail::StorageUniquerImpl::StorageKeyInfo::isEqual(), and mlir::ElementsAttr::mapValues().
The documentation for this class was generated from the following file:
include/mlir/Support/StorageUniquer.h