MLIR: mlir::Builder Class Reference
mlir::Builder Class Reference
This class is a general helper class for creating context-global objects like types, attributes, and affine expressions.
#include "mlir/IR/Builders.h"
Public Member Functions
Builder (MLIRContext *context)
Builder (ModuleOp module)
MLIRContext * getContext () const
Identifier getIdentifier (StringRef str)
Location getUnknownLoc ()
Location getFileLineColLoc (Identifier filename, unsigned line, unsigned column)
Location getFusedLoc (ArrayRef< Location > locs, Attribute metadata=Attribute())
FloatType getBF16Type ()
FloatType getF16Type ()
FloatType getF32Type ()
FloatType getF64Type ()
IndexType getIndexType ()
IntegerType getI1Type ()
IntegerType getIntegerType (unsigned width)
IntegerType getIntegerType (unsigned width, bool isSigned)
FunctionType getFunctionType (ArrayRef< Type > inputs, ArrayRef< Type > results)
TupleType getTupleType (ArrayRef< Type > elementTypes)
NoneType getNoneType ()
template<typename Ty , typename... Args>
Ty getType (Args... args)
Get or construct an instance of the type 'ty' with provided arguments.
NamedAttribute getNamedAttr (StringRef name, Attribute val)
UnitAttr getUnitAttr ()
BoolAttr getBoolAttr (bool value)
DictionaryAttr getDictionaryAttr (ArrayRef< NamedAttribute > value)
IntegerAttr getIntegerAttr (Type type, int64_t value)
IntegerAttr getIntegerAttr (Type type, const APInt &value)
FloatAttr getFloatAttr (Type type, double value)
FloatAttr getFloatAttr (Type type, const APFloat &value)
StringAttr getStringAttr (StringRef bytes)
ArrayAttr getArrayAttr (ArrayRef< Attribute > value)
FlatSymbolRefAttr getSymbolRefAttr (Operation *value)
FlatSymbolRefAttr getSymbolRefAttr (StringRef value)
SymbolRefAttr getSymbolRefAttr (StringRef value, ArrayRef< FlatSymbolRefAttr > nestedReferences)
Attribute getZeroAttr (Type type)
FloatAttr getF16FloatAttr (float value)
FloatAttr getF32FloatAttr (float value)
FloatAttr getF64FloatAttr (double value)
IntegerAttr getI8IntegerAttr (int8_t value)
IntegerAttr getI16IntegerAttr (int16_t value)
IntegerAttr getI32IntegerAttr (int32_t value)
IntegerAttr getI64IntegerAttr (int64_t value)
IntegerAttr getIndexAttr (int64_t value)
IntegerAttr getSI32IntegerAttr (int32_t value)
Signed and unsigned integer attribute getters.
IntegerAttr getUI32IntegerAttr (uint32_t value)
DenseIntElementsAttr getI32VectorAttr (ArrayRef< int32_t > values)
Vector-typed DenseIntElementsAttr getters. values must not be empty.
DenseIntElementsAttr getI64VectorAttr (ArrayRef< int64_t > values)
DenseIntElementsAttr getI32TensorAttr (ArrayRef< int32_t > values)
Tensor-typed DenseIntElementsAttr getters.
DenseIntElementsAttr getI64TensorAttr (ArrayRef< int64_t > values)
ArrayAttr getAffineMapArrayAttr (ArrayRef< AffineMap > values)
ArrayAttr getI32ArrayAttr (ArrayRef< int32_t > values)
ArrayAttr getI64ArrayAttr (ArrayRef< int64_t > values)
ArrayAttr getIndexArrayAttr (ArrayRef< int64_t > values)
ArrayAttr getF32ArrayAttr (ArrayRef< float > values)
ArrayAttr getF64ArrayAttr (ArrayRef< double > values)
ArrayAttr getStrArrayAttr (ArrayRef< StringRef > values)
AffineExpr getAffineDimExpr (unsigned position)
AffineExpr getAffineSymbolExpr (unsigned position)
AffineExpr getAffineConstantExpr (int64_t constant)
AffineMap getEmptyAffineMap ()
Returns a zero result affine map with no dimensions or symbols: () -> ().
AffineMap getConstantAffineMap (int64_t val)
Returns a single constant result affine map with 0 dimensions and 0 symbols.
AffineMap getDimIdentityMap ()
AffineMap getMultiDimIdentityMap (unsigned rank)
AffineMap getSymbolIdentityMap ()
AffineMap getSingleDimShiftAffineMap (int64_t shift)
Returns a map that shifts its (single) input dimension by 'shift'.
AffineMap getShiftedAffineMap (AffineMap map, int64_t shift)
Returns an affine map that is a translation (shift) of all result expressions in 'map' by 'shift'.
Protected Attributes
MLIRContext * context
Detailed Description
This class is a general helper class for creating context-global objects like types, attributes, and affine expressions.
Definition at line 47 of file Builders.h.
Constructor & Destructor Documentation
Builder() [1/2]
mlir::Builder::Builder (MLIRContext * context) inline explicit
Definition at line 49 of file Builders.h.
Builder() [2/2]
Builder::Builder (ModuleOp module) explicit
Definition at line 20 of file Builders.cpp.
Member Function Documentation
getAffineConstantExpr()
AffineExpr Builder::getAffineConstantExpr (int64_t constant)
Definition at line 288 of file Builders.cpp.
References context, and mlir::getAffineConstantExpr().
Referenced by getConstantAffineMap(), getType(), and verify().
getAffineDimExpr()
AffineExpr Builder::getAffineDimExpr (unsigned position)
Definition at line 280 of file Builders.cpp.
References context, and mlir::getAffineDimExpr().
Referenced by augmentMapAndBounds(), createPrivateMemRef(), generateCopy(), generatePointWiseCopy(), getCleanupLoopLowerBound(), getDimIdentityMap(), getMultiDimIdentityMap(), getSingleDimShiftAffineMap(), getType(), mlir::loopUnrollJamByFactor(), and processParallelLoop().
getAffineMapArrayAttr()
ArrayAttr Builder::getAffineMapArrayAttr (ArrayRef< AffineMap > values)
Definition at line 243 of file Builders.cpp.
References mlir::AffineMapAttr::get(), and getArrayAttr().
Referenced by buildNamedStructuredOpRegionAndAttributes(), computeTensorReshapeCollapsedType(), getSymbolLessAffineMaps(), getType(), isIdentitySuffix(), and print().
getAffineSymbolExpr()
AffineExpr Builder::getAffineSymbolExpr (unsigned position)
Definition at line 284 of file Builders.cpp.
References context, and mlir::getAffineSymbolExpr().
Referenced by getSymbolIdentityMap(), getType(), and processParallelLoop().
getArrayAttr()
ArrayAttr Builder::getArrayAttr (ArrayRef< Attribute > value)
Definition at line 186 of file Builders.cpp.
References context, and mlir::ArrayAttr::get().
Referenced by extractSymbolReference(), fuseLinalgOpsGreedily(), getAffineMapArrayAttr(), getF32ArrayAttr(), getF64ArrayAttr(), getI32ArrayAttr(), getI64ArrayAttr(), getIndexArrayAttr(), getStrArrayAttr(), getType(), isFnEntryBlock(), isIdentitySuffix(), isTensorReshapeOpFusible(), parseBranchConditionalOp(), parseEntryPointOp(), parseVerCapExtAttr(), verify(), and mlir::spirv::InterfaceVarABIAttr::verifyConstructionInvariants().
getBF16Type()
FloatType Builder::getBF16Type ()
Definition at line 45 of file Builders.cpp.
References context, and mlir::FloatType::getBF16().
Referenced by getContext(), and parseSymbol().
getBoolAttr()
BoolAttr Builder::getBoolAttr (bool value)
Definition at line 87 of file Builders.cpp.
References context, and mlir::BoolAttr::get().
Referenced by convertBoolAttr(), extractSymbolReference(), getType(), getZeroAttr(), hoistAffineIfOp(), parseAffinePrefetchOp(), parsePrefetchOp(), and verify().
getConstantAffineMap()
AffineMap Builder::getConstantAffineMap (int64_t val)
Returns a single constant result affine map with 0 dimensions and 0 symbols.
One constant result: () -> (val).
Definition at line 294 of file Builders.cpp.
References mlir::AffineMap::get(), and getAffineConstantExpr().
Referenced by getType().
getContext()
MLIRContext* mlir::Builder::getContext () const inline
Definition at line 52 of file Builders.h.
References context, getBF16Type(), getF16Type(), getF32Type(), getF64Type(), getFileLineColLoc(), getFunctionType(), getFusedLoc(), getI1Type(), getIdentifier(), getIndexType(), getIntegerType(), getNoneType(), getTupleType(), and getUnknownLoc().
Referenced by augmentMapAndBounds(), buildLLVMFunctionType(), buildNamedStructuredOpRegionAndAttributes(), createFullTiles(), mlir::AffineDmaWaitOp::fold(), generateCopy(), generateExtractSlicesOpResultType(), generatePointWiseCopy(), generateTransferOpSlices(), getCleanupLoopLowerBound(), mlir::edsc::ScopedContext::getContext(), mlir::spirv::getElementPtr(), getIndexArrayAttr(), getLibraryCallSymbolRef(), getLlvmDialect(), getLocalInvocationDimSize(), getSymbolRefAttr(), isIdentitySuffix(), lowerAsEntryFunction(), makeTiledViews(), mlir::operator<<(), parseAtomicCmpXchgOp(), parseCallOp(), parseCmpOp(), parseConstShapeOp(), parseElementAttrHexValues(), parseGlobalOp(), parseInvokeOp(), parseTupleOp(), mlir::LLVMTypeConverter::promoteOneMemRefDescriptor(), mlir::linalg::LinalgMarker::replaceLinalgMarker(), resolveSourceIndices(), mlir::loop::tileParallelLoop(), and verify().
getDictionaryAttr()
DictionaryAttr Builder::getDictionaryAttr (ArrayRef< NamedAttribute > value)
Definition at line 91 of file Builders.cpp.
References context, and mlir::DictionaryAttr::get().
Referenced by mlir::impl::addArgAndResultAttrs(), extractSymbolReference(), and getType().
getDimIdentityMap()
AffineMap Builder::getDimIdentityMap ()
Definition at line 299 of file Builders.cpp.
References mlir::AffineMap::get(), and getAffineDimExpr().
Referenced by getType(), mapParallelOp(), and mlir::promoteIfSingleIteration().
getEmptyAffineMap()
AffineMap Builder::getEmptyAffineMap ()
Returns a zero result affine map with no dimensions or symbols: () -> ().
Definition at line 292 of file Builders.cpp.
References context, and mlir::AffineMap::get().
Referenced by getType(), print(), and verify().
getF16FloatAttr()
FloatAttr Builder::getF16FloatAttr (float value)
Definition at line 170 of file Builders.cpp.
References mlir::FloatAttr::get(), and getF16Type().
Referenced by getType().
getF16Type()
FloatType Builder::getF16Type ()
Definition at line 47 of file Builders.cpp.
References context, and mlir::FloatType::getF16().
Referenced by getContext(), getF16FloatAttr(), and parseSymbol().
getF32ArrayAttr()
ArrayAttr Builder::getF32ArrayAttr (ArrayRef< float > values)
Definition at line 225 of file Builders.cpp.
References getArrayAttr(), and getF32FloatAttr().
Referenced by getType().
getF32FloatAttr()
FloatAttr Builder::getF32FloatAttr (float value)
Definition at line 166 of file Builders.cpp.
References mlir::FloatAttr::get(), and getF32Type().
Referenced by convertFloatAttr(), getF32ArrayAttr(), and getType().
getF32Type()
FloatType Builder::getF32Type ()
Definition at line 49 of file Builders.cpp.
References context, and mlir::FloatType::getF32().
Referenced by getContext(), getF32FloatAttr(), and parseSymbol().
getF64ArrayAttr()
ArrayAttr Builder::getF64ArrayAttr (ArrayRef< double > values)
Definition at line 231 of file Builders.cpp.
References getArrayAttr(), and getF64FloatAttr().
Referenced by getType().
getF64FloatAttr()
FloatAttr Builder::getF64FloatAttr (double value)
Definition at line 162 of file Builders.cpp.
References mlir::FloatAttr::get(), and getF64Type().
Referenced by getF64ArrayAttr(), and getType().
getF64Type()
FloatType Builder::getF64Type ()
Definition at line 51 of file Builders.cpp.
References context, and mlir::FloatType::getF64().
Referenced by extractSymbolReference(), getContext(), getF64FloatAttr(), and parseSymbol().
getFileLineColLoc()
Location Builder::getFileLineColLoc (Identifier filename, unsigned line, unsigned column)
Definition at line 32 of file Builders.cpp.
References context, and mlir::FileLineColLoc::get().
Referenced by getContext(), and isFnEntryBlock().
getFloatAttr() [1/2]
FloatAttr Builder::getFloatAttr (Type type, double value)
Definition at line 174 of file Builders.cpp.
References mlir::FloatAttr::get().
Referenced by mlir::ConstantFloatOp::build(), getI64SubArray(), getType(), getZeroAttr(), and mlir::LLVM::detail::vectorOneToOneRewrite().
getFloatAttr() [2/2]
FloatAttr Builder::getFloatAttr (Type type, const APFloat & value)
Definition at line 178 of file Builders.cpp.
References mlir::FloatAttr::get().
getFunctionType()
FunctionType Builder::getFunctionType (ArrayRef< Type > inputs, ArrayRef< Type > results)
Definition at line 66 of file Builders.cpp.
References context, and mlir::FunctionType::get().
Referenced by getContext(), lowerAsEntryFunction(), lowerEntryPointABIAttr(), mlir::FunctionAndBlockSignatureConverter::matchAndRewrite(), mlir::FuncOp::parse(), parseFuncOp(), parseGPUFuncOp(), parseSymbol(), and mlir::SPIRVTypeConverter::SPIRVTypeConverter().
getFusedLoc()
Location Builder::getFusedLoc (ArrayRef< Location > locs, Attribute metadata = Attribute())
Definition at line 37 of file Builders.cpp.
References context, and mlir::FusedLoc::get().
Referenced by getContext().
getI16IntegerAttr()
IntegerAttr Builder::getI16IntegerAttr (int16_t value)
Definition at line 143 of file Builders.cpp.
References mlir::IntegerAttr::get(), and getIntegerType().
Referenced by getType().
getI1Type()
IntegerType Builder::getI1Type ()
Definition at line 55 of file Builders.cpp.
References context, and mlir::IntegerType::get().
Referenced by getContext(), parseBranchConditionalOp(), parseContractionOp(), parseSelectOp(), parseShuffleOp(), and verify().
getI32ArrayAttr()
ArrayAttr Builder::getI32ArrayAttr (ArrayRef< int32_t > values)
Definition at line 205 of file Builders.cpp.
References getArrayAttr(), and getI32IntegerAttr().
Referenced by getLaunchConfigIndex(), getLocalInvocationDimSize(), getType(), parseExecutionModeOp(), mlir::LLVM::detail::vectorOneToOneRewrite(), and verify().
getI32IntegerAttr()
IntegerAttr Builder::getI32IntegerAttr (int32_t value)
Definition at line 129 of file Builders.cpp.
References mlir::IntegerAttr::get(), and getIntegerType().
Referenced by mlir::ModuleOp::build(), getI32ArrayAttr(), getLinkageAttrName(), getType(), isFnEntryBlock(), mlir::GPUFuncOpLowering< AllocaAddrSpace >::matchAndRewrite(), parseEnumKeywordAttr(), parseEnumStrAttr(), parseInterfaceVarABIAttr(), parseLoopOp(), parseSelectionOp(), parseVariableOp(), parseVerCapExtAttr(), print(), mlir::LLVM::detail::vectorOneToOneRewrite(), verify(), and mlir::spirv::InterfaceVarABIAttr::verifyConstructionInvariants().
getI32TensorAttr()
DenseIntElementsAttr Builder::getI32TensorAttr (ArrayRef< int32_t > values)
Tensor-typed DenseIntElementsAttr getters.
values can be empty. These are generally preferable for representing general lists of integers as attributes.
Definition at line 115 of file Builders.cpp.
References mlir::RankedTensorType::get(), mlir::DenseIntElementsAttr::get(), and getIntegerType().
Referenced by getType().
getI32VectorAttr()
DenseIntElementsAttr Builder::getI32VectorAttr (ArrayRef< int32_t > values)
Vector-typed DenseIntElementsAttr getters. values must not be empty.
Definition at line 103 of file Builders.cpp.
References mlir::VectorType::get(), mlir::DenseIntElementsAttr::get(), and getIntegerType().
Referenced by getType(), parseBranchConditionalOp(), parseInvokeOp(), parseParallelOp(), and print().
getI64ArrayAttr()
ArrayAttr Builder::getI64ArrayAttr (ArrayRef< int64_t > values)
Definition at line 211 of file Builders.cpp.
References getArrayAttr(), and getI64IntegerAttr().
Referenced by convertRangeType(), extractOne(), mlir::StructBuilder::extractPtr(), getType(), mlir::vector::getVectorSubscriptAttr(), insertOne(), isIdentitySuffix(), matchAndRewriteOneToOne(), matchSimpleAtomicOp(), nDVectorIterate(), mlir::MemRefDescriptor::offset(), mlir::LLVM::detail::oneToOneRewrite(), parseAffineParallelOp(), mlir::MemRefDescriptor::setOffset(), mlir::StructBuilder::setPtr(), mlir::MemRefDescriptor::setSize(), mlir::MemRefDescriptor::setStride(), mlir::MemRefDescriptor::size(), mlir::MemRefDescriptor::stride(), unrollSingleResultStructuredOp(), mlir::LLVM::detail::vectorOneToOneRewrite(), and verify().
getI64IntegerAttr()
IntegerAttr Builder::getI64IntegerAttr (int64_t value)
Definition at line 99 of file Builders.cpp.
References mlir::IntegerAttr::get(), and getIntegerType().
Referenced by buildCmpFOp(), buildCmpIOp(), findMatchingStartFinishInsts(), fuseLinalgOpsGreedily(), getI64ArrayAttr(), getLinkageAttrName(), getOrCreateUnrolledVectorSlice(), mlir::gpu::getParallelLoopDimMappingAttr(), getType(), isIdentitySuffix(), isTensorReshapeOpFusible(), mlir::GPUFuncOpLowering< AllocaAddrSpace >::matchAndRewrite(), parseAtomicBinOp(), parseAtomicOrdering(), parseCmpOp(), parseGlobalOp(), parseGPUFuncOp(), parseLLVMFuncOp(), parseOptionalLLVMKeyword(), parseShuffleVectorOp(), mlir::LLVM::detail::vectorOneToOneRewrite(), and verify().
getI64TensorAttr()
DenseIntElementsAttr Builder::getI64TensorAttr (ArrayRef< int64_t > values)
Definition at line 122 of file Builders.cpp.
References mlir::RankedTensorType::get(), mlir::DenseIntElementsAttr::get(), and getIntegerType().
Referenced by getType(), and parseConstShapeOp().
getI64VectorAttr()
DenseIntElementsAttr Builder::getI64VectorAttr (ArrayRef< int64_t > values)
Definition at line 109 of file Builders.cpp.
References mlir::VectorType::get(), mlir::DenseIntElementsAttr::get(), and getIntegerType().
Referenced by getType().
getI8IntegerAttr()
IntegerAttr Builder::getI8IntegerAttr (int8_t value)
Definition at line 147 of file Builders.cpp.
References mlir::IntegerAttr::get(), and getIntegerType().
Referenced by getType().
getIdentifier()
Identifier Builder::getIdentifier (StringRef str)
Definition at line 22 of file Builders.cpp.
References context, and mlir::Identifier::get().
Referenced by extractSymbolReference(), getContext(), getNamedAttr(), hoistAffineIfOp(), and isFnEntryBlock().
getIndexArrayAttr()
ArrayAttr Builder::getIndexArrayAttr (ArrayRef< int64_t > values)
Definition at line 217 of file Builders.cpp.
References mlir::IndexType::get(), getArrayAttr(), getContext(), and getIntegerAttr().
Referenced by getType().
getIndexAttr()
IntegerAttr Builder::getIndexAttr (int64_t value)
Definition at line 95 of file Builders.cpp.
References mlir::IntegerAttr::get(), and getIndexType().
Referenced by getType().
getIndexType()
IndexType Builder::getIndexType ()
Definition at line 53 of file Builders.cpp.
References context, and mlir::IndexType::get().
Referenced by mlir::ConstantIndexOp::build(), convertRangeType(), createForAllDimensions(), mlir::LLVM::createGlobalString(), createIndexAttrConstant(), extractOne(), mlir::AffineDmaWaitOp::fold(), getContext(), getI64SubArray(), getIndexAttr(), getLibraryCallSymbolRef(), insertCopyLoops(), insertOne(), makeTiledViews(), mlir::DmaStartOp::parse(), mlir::AffineDmaStartOp::parse(), mlir::DmaWaitOp::parse(), mlir::AffineDmaWaitOp::parse(), parseAffineApplyOp(), parseAffineForOp(), parseAffineLoadOp(), parseAffineMinMaxOp(), parseAffineParallelOp(), parseAffinePrefetchOp(), parseAffineStoreOp(), parseConstShapeOp(), mlir::parseDimAndSymbolList(), parseDimOp(), parseForOp(), parseGenericAtomicRMWOp(), parseLaunchOp(), parseParallelOp(), parsePrefetchOp(), parseShuffleOp(), parseSymbol(), parseTransferReadOp(), parseTupleGetOp(), parseViewOp(), print(), mlir::loop::tileParallelLoop(), mlir::LLVM::detail::vectorOneToOneRewrite(), and wrapExternalFunction().
getIntegerAttr() [1/2]
IntegerAttr Builder::getIntegerAttr (Type type, int64_t value)
Definition at line 151 of file Builders.cpp.
References mlir::IntegerAttr::get(), mlir::Type::getIntOrFloatBitWidth(), mlir::Type::isIndex(), and mlir::Type::isSignedInteger().
Referenced by adjustAccessChainForBitwidth(), mlir::ConstantIntOp::build(), mlir::ConstantIndexOp::build(), buildAttributeAPInt(), convertIntegerAttr(), convertRangeType(), mlir::LLVM::createGlobalString(), createIndexAttrConstant(), extractCompositeElement(), extractOne(), mlir::AffineDmaWaitOp::fold(), getI64SubArray(), getIndexArrayAttr(), getLibraryCallSymbolRef(), getOffsetForBitwidth(), getType(), getZeroAttr(), insertOne(), parseAffineForOp(), resolveSourceIndices(), shiftValue(), verify(), and wrapExternalFunction().
getIntegerAttr() [2/2]
IntegerAttr Builder::getIntegerAttr (Type type, const APInt & value)
Definition at line 158 of file Builders.cpp.
References mlir::IntegerAttr::get().
getIntegerType() [1/2]
IntegerType Builder::getIntegerType (unsigned width)
Definition at line 57 of file Builders.cpp.
References context, and mlir::IntegerType::get().
Referenced by adjustAccessChainForBitwidth(), mlir::ConstantIntOp::build(), buildAttributeAPInt(), convertRangeType(), getContext(), getI16IntegerAttr(), getI32IntegerAttr(), getI32TensorAttr(), getI32VectorAttr(), getI64IntegerAttr(), getI64SubArray(), getI64TensorAttr(), getI64VectorAttr(), getI8IntegerAttr(), getLaunchConfigIndex(), getOffsetForBitwidth(), getOrInsertBuiltinVariable(), getSI32IntegerAttr(), getUI32IntegerAttr(), getUnaryOpResultType(), mlir::vector::getVectorSubscriptType(), parseAccessChainOp(), parseAffinePrefetchOp(), parseBranchConditionalOp(), parseElementAttrHexValues(), parseExecutionModeOp(), parseGroupNonUniformArithmeticOp(), parseIfOp(), parseMemoryAccessAttributes(), parsePrefetchOp(), parseShuffleOp(), parseStorageType(), parseVariableDecorations(), shiftValue(), and mlir::LLVM::detail::vectorOneToOneRewrite().
getIntegerType() [2/2]
IntegerType Builder::getIntegerType (unsigned width, bool isSigned)
Definition at line 61 of file Builders.cpp.
References context, mlir::IntegerType::get(), mlir::IntegerType::Signed, and mlir::IntegerType::Unsigned.
getMultiDimIdentityMap()
AffineMap Builder::getMultiDimIdentityMap (unsigned rank)
Definition at line 303 of file Builders.cpp.
References context, mlir::AffineMap::get(), and getAffineDimExpr().
Referenced by mlir::createAffineComputationSlice(), generateCopy(), getType(), mlir::edsc::makeAffineLoopBuilder(), mlir::normalizeMemRef(), print(), mlir::replaceAllMemRefUsesWith(), vectorizeOneOperation(), vectorizeRootOrTerminal(), and verify().
getNamedAttr()
NamedAttribute Builder::getNamedAttr (StringRef name, Attribute val)
Definition at line 81 of file Builders.cpp.
References getIdentifier().
Referenced by getType(), vectorizeConstant(), verify(), and wrapExternalFunction().
getNoneType()
NoneType Builder::getNoneType ()
Definition at line 75 of file Builders.cpp.
References context, and mlir::NoneType::get().
Referenced by getContext(), parseEnumStrAttr(), and parseSymbol().
getShiftedAffineMap()
AffineMap Builder::getShiftedAffineMap (AffineMap map, int64_t shift)
Returns an affine map that is a translation (shift) of all result expressions in 'map' by 'shift'.
Eg: input: (d0, d1)[s0] -> (d0, d1 + s0), shift = 2 returns: (d0, d1)[s0] -> (d0 + 2, d1 + s0 + 2)
Definition at line 323 of file Builders.cpp.
References context, mlir::AffineMap::get(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), and mlir::AffineMap::getResults().
Referenced by mlir::affineForOpBodySkew(), and getType().
getSI32IntegerAttr()
IntegerAttr Builder::getSI32IntegerAttr (int32_t value)
Signed and unsigned integer attribute getters.
Definition at line 133 of file Builders.cpp.
References mlir::IntegerAttr::get(), and getIntegerType().
Referenced by getType().
getSingleDimShiftAffineMap()
AffineMap Builder::getSingleDimShiftAffineMap (int64_t shift)
Returns a map that shifts its (single) input dimension by 'shift'.
(d0) -> (d0 + shift)
Definition at line 317 of file Builders.cpp.
References mlir::AffineMap::get(), and getAffineDimExpr().
Referenced by getType().
getStrArrayAttr()
ArrayAttr Builder::getStrArrayAttr (ArrayRef< StringRef > values)
Definition at line 237 of file Builders.cpp.
References getArrayAttr(), and getStringAttr().
Referenced by buildNamedStructuredOpRegionAndAttributes(), getStrArrayAttrForEnumList(), getType(), and print().
getStringAttr()
StringAttr Builder::getStringAttr (StringRef bytes)
Definition at line 182 of file Builders.cpp.
References context, and mlir::StringAttr::get().
Referenced by mlir::FuncOp::build(), createForAllDimensions(), mlir::LLVM::createGlobalString(), getLinkageAttrName(), getStrArrayAttr(), getType(), insertCopyLoops(), isIdentitySuffix(), parseFenceOp(), parseShuffleOp(), parseShuffleVectorOp(), parseVerCapExtAttr(), print(), mlir::linalg::LinalgMarker::replaceLinalgMarker(), verify(), and mlir::spirv::InterfaceVarABIAttr::verifyConstructionInvariants().
getSymbolIdentityMap()
AffineMap Builder::getSymbolIdentityMap ()
Definition at line 312 of file Builders.cpp.
References mlir::AffineMap::get(), and getAffineSymbolExpr().
Referenced by getType().
getSymbolRefAttr() [1/3]
FlatSymbolRefAttr Builder::getSymbolRefAttr (Operation * value)
Definition at line 190 of file Builders.cpp.
References mlir::Operation::getAttrOfType(), and mlir::SymbolTable::getSymbolAttrName().
Referenced by extractSymbolReference(), getI64SubArray(), getLibraryCallSymbolRef(), getType(), isFnEntryBlock(), mlir::OpToFuncCallLowering< SourceOp >::matchAndRewrite(), parseLaunchOp(), mlir::LLVM::detail::vectorOneToOneRewrite(), and verify().
getSymbolRefAttr() [2/3]
FlatSymbolRefAttr Builder::getSymbolRefAttr (StringRef value)
Definition at line 196 of file Builders.cpp.
References mlir::SymbolRefAttr::get(), and getContext().
getSymbolRefAttr() [3/3]
SymbolRefAttr Builder::getSymbolRefAttr (StringRef value, ArrayRef< FlatSymbolRefAttr > nestedReferences)
Definition at line 200 of file Builders.cpp.
References mlir::SymbolRefAttr::get(), and getContext().
getTupleType()
TupleType Builder::getTupleType (ArrayRef< Type > elementTypes)
Definition at line 71 of file Builders.cpp.
References context, and mlir::TupleType::get().
Referenced by getContext(), and unrollSingleResultStructuredOp().
getType()
template<typename Ty , typename... Args> Ty mlir::Builder::getType (Args... args) inline
Get or construct an instance of the type 'ty' with provided arguments.
Definition at line 79 of file Builders.h.
References context, getAffineConstantExpr(), getAffineDimExpr(), getAffineMapArrayAttr(), getAffineSymbolExpr(), getArrayAttr(), getBoolAttr(), getConstantAffineMap(), getDictionaryAttr(), getDimIdentityMap(), getEmptyAffineMap(), getF16FloatAttr(), getF32ArrayAttr(), getF32FloatAttr(), getF64ArrayAttr(), getF64FloatAttr(), getFloatAttr(), getI16IntegerAttr(), getI32ArrayAttr(), getI32IntegerAttr(), getI32TensorAttr(), getI32VectorAttr(), getI64ArrayAttr(), getI64IntegerAttr(), getI64TensorAttr(), getI64VectorAttr(), getI8IntegerAttr(), getIndexArrayAttr(), getIndexAttr(), getIntegerAttr(), getMultiDimIdentityMap(), getNamedAttr(), getShiftedAffineMap(), getSI32IntegerAttr(), getSingleDimShiftAffineMap(), getStrArrayAttr(), getStringAttr(), getSymbolIdentityMap(), getSymbolRefAttr(), getUI32IntegerAttr(), getUnitAttr(), and getZeroAttr().
Referenced by mlir::OpBuilder::tryFold().
getUI32IntegerAttr()
IntegerAttr Builder::getUI32IntegerAttr (uint32_t value)
Definition at line 138 of file Builders.cpp.
References mlir::IntegerAttr::get(), and getIntegerType().
Referenced by getType().
getUnitAttr()
UnitAttr Builder::getUnitAttr ()
Definition at line 85 of file Builders.cpp.
References context, and mlir::UnitAttr::get().
Referenced by extractSymbolReference(), getLinkageAttrName(), getType(), parseGlobalOp(), parseGPUFuncOp(), and parseLandingpadOp().
getUnknownLoc()
Location Builder::getUnknownLoc ()
Definition at line 30 of file Builders.cpp.
References context, and mlir::UnknownLoc::get().
Referenced by buildNamedStructuredOpRegionAndAttributes(), fuseLinalgOpsGreedily(), getContext(), isTensorReshapeOpFusible(), logFailure(), and mlir::LLVM::detail::vectorOneToOneRewrite().
getZeroAttr()
Attribute Builder::getZeroAttr (Type type)
Definition at line 249 of file Builders.cpp.
References mlir::StandardTypes::BF16, mlir::Type::cast(), mlir::StandardTypes::F16, mlir::StandardTypes::F32, mlir::StandardTypes::F64, mlir::DenseElementsAttr::get(), getBoolAttr(), getFloatAttr(), getIntegerAttr(), mlir::Type::getKind(), mlir::StandardTypes::Integer, mlir::StandardTypes::RankedTensor, and mlir::StandardTypes::Vector.
Referenced by getI64SubArray(), getInputAndOutputIndices(), getType(), isIdentitySuffix(), mlir::LLVM::detail::vectorOneToOneRewrite(), and verify().
Member Data Documentation
context
MLIRContext* mlir::Builder::context protected
Definition at line 167 of file Builders.h.
Referenced by getAffineConstantExpr(), getAffineDimExpr(), getAffineSymbolExpr(), getArrayAttr(), getBF16Type(), getBoolAttr(), getContext(), getDictionaryAttr(), getEmptyAffineMap(), getF16Type(), getF32Type(), getF64Type(), getFileLineColLoc(), getFunctionType(), getFusedLoc(), getI1Type(), getIdentifier(), getIndexType(), getIntegerType(), getMultiDimIdentityMap(), getNoneType(), getShiftedAffineMap(), getStringAttr(), getTupleType(), getType(), getUnitAttr(), getUnknownLoc(), and mlir::OpBuilder::tryFold().
The documentation for this class was generated from the following files:
include/mlir/IR/Builders.h
lib/IR/Builders.cpp