MLIR: mlir::spirv::StructType Class Reference
mlir::spirv::StructType Class Reference
#include "mlir/Dialect/SPIRV/SPIRVTypes.h"
Classes
class ElementTypeRange
Range class for element types.
Public Types
using LayoutInfo = uint64_t
using MemberDecorationInfo = std::pair< uint32_t, spirv::Decoration >
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Public Member Functions
unsigned getNumElements () const
Type getElementType (unsigned) const
ElementTypeRange getElementTypes () const
bool hasLayout () const
uint64_t getOffset (unsigned) const
void getMemberDecorations (SmallVectorImpl< StructType::MemberDecorationInfo > &allMemberDecorations) const
void getMemberDecorations (unsigned i, SmallVectorImpl< spirv::Decoration > &memberDecorations) const
void getExtensions (SPIRVType::ExtensionArrayRefVector &extensions, Optional< spirv::StorageClass > storage=llvm::None)
void getCapabilities (SPIRVType::CapabilityArrayRefVector &capabilities, Optional< spirv::StorageClass > storage=llvm::None)
Static Public Member Functions
static bool kindof (unsigned kind)
static StructType get (ArrayRef< Type > memberTypes, ArrayRef< LayoutInfo > layoutInfo={}, ArrayRef< MemberDecorationInfo > memberDecorations={})
Construct a StructType with at least one member.
static StructType getEmpty (MLIRContext *context)
Construct a struct with no members.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Additional Inherited Members
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Definition at line 261 of file SPIRVTypes.h.
Member Typedef Documentation
LayoutInfo
using mlir::spirv::StructType::LayoutInfo = uint64_t
Definition at line 273 of file SPIRVTypes.h.
MemberDecorationInfo
using mlir::spirv::StructType::MemberDecorationInfo = std::pair<uint32_t, spirv::Decoration>
Definition at line 275 of file SPIRVTypes.h.
Member Function Documentation
get()
StructType StructType::get (ArrayRef< Type > memberTypes, ArrayRef< LayoutInfo > layoutInfo = {}, ArrayRef< MemberDecorationInfo > memberDecorations = {}) static
Construct a StructType with at least one member.
Definition at line 842 of file SPIRVTypes.cpp.
References mlir::spirv::TypeKind::Struct.
Referenced by convertMemrefType(), createGlobalVarForEntryPointArgument(), mlir::VulkanLayoutUtils::decorateType(), isFnEntryBlock(), and parseStructType().
getCapabilities()
void StructType::getCapabilities (SPIRVType::CapabilityArrayRefVector & capabilities, Optional< spirv::StorageClass > storage = llvm::None)
Definition at line 911 of file SPIRVTypes.cpp.
getElementType()
Type StructType::getElementType (unsigned index) const
Definition at line 864 of file SPIRVTypes.cpp.
Referenced by mlir::VulkanLayoutUtils::decorateType(), and print().
getElementTypes()
StructType::ElementTypeRange StructType::getElementTypes () const
Definition at line 869 of file SPIRVTypes.cpp.
getEmpty()
StructType StructType::getEmpty (MLIRContext * context) static
Construct a struct with no members.
Definition at line 854 of file SPIRVTypes.cpp.
References mlir::spirv::TypeKind::Struct.
Referenced by isFnEntryBlock(), and parseStructType().
getExtensions()
void StructType::getExtensions (SPIRVType::ExtensionArrayRefVector & extensions, Optional< spirv::StorageClass > storage = llvm::None)
Definition at line 905 of file SPIRVTypes.cpp.
getMemberDecorations() [1/2]
void StructType::getMemberDecorations (SmallVectorImpl< StructType::MemberDecorationInfo > & allMemberDecorations) const
Definition at line 880 of file SPIRVTypes.cpp.
Referenced by mlir::VulkanLayoutUtils::decorateType(), and print().
getMemberDecorations() [2/2]
void StructType::getMemberDecorations (unsigned i, SmallVectorImpl< spirv::Decoration > & memberDecorations) const
Definition at line 889 of file SPIRVTypes.cpp.
getNumElements()
unsigned StructType::getNumElements () const
Definition at line 860 of file SPIRVTypes.cpp.
Referenced by mlir::VulkanLayoutUtils::decorateType(), mlir::VulkanLayoutUtils::isLegalType(), and print().
getOffset()
uint64_t StructType::getOffset (unsigned index) const
Definition at line 875 of file SPIRVTypes.cpp.
Referenced by print().
hasLayout()
bool StructType::hasLayout () const
Definition at line 873 of file SPIRVTypes.cpp.
Referenced by mlir::VulkanLayoutUtils::isLegalType(), and print().
kindof()
static bool mlir::spirv::StructType::kindof (unsigned kind) inline static
Definition at line 277 of file SPIRVTypes.h.
References getElementType(), and mlir::spirv::TypeKind::Struct.
The documentation for this class was generated from the following files:
include/mlir/Dialect/SPIRV/SPIRVTypes.h
lib/Dialect/SPIRV/SPIRVTypes.cpp