MLIR: mlir::TypeConverter Class Reference
mlir::TypeConverter Class Reference
Base class for type conversion interface.
#include "mlir/Transforms/DialectConversion.h"
Classes
class SignatureConversion
This class provides all of the information necessary to convert a type signature.
Public Member Functions
virtual ~TypeConverter ()=default
template<typename FnT , typename T = typename llvm::function_traits<FnT>::template arg_t<0>>
void addConversion (FnT &&callback)
Register a conversion function.
LogicalResult convertType (Type t, SmallVectorImpl< Type > &results)
Convert the given type.
Type convertType (Type t)
This hook simplifies defining 1-1 type conversions.
LogicalResult convertTypes (ArrayRef< Type > types, SmallVectorImpl< Type > &results)
Convert the given set of types, filling 'results' as necessary.
bool isLegal (Type type)
Return true if the given type is legal for this type converter, i.e.
bool isSignatureLegal (FunctionType funcType)
Return true if the inputs and outputs of the given function type are legal.
virtual LogicalResult convertSignatureArg (unsigned inputNo, Type type, SignatureConversion &result)
This hook allows for converting a specific argument of a signature.
Optional< SignatureConversion > convertBlockSignature (Block *block)
This function converts the type signature of the given block, by invoking 'convertSignatureArg' for each argument.
virtual Operation * materializeConversion (PatternRewriter &rewriter, Type resultType, ArrayRef< Value > inputs, Location loc)
This hook allows for materializing a conversion from a set of types into one result type by generating a cast operation of some kind.
Detailed Description
Base class for type conversion interface.
Specific converters must derive this class and implement the pure virtual functions.
Definition at line 39 of file DialectConversion.h.
Constructor & Destructor Documentation
~TypeConverter()
virtual mlir::TypeConverter::~TypeConverter () virtual default
Member Function Documentation
addConversion()
template<typename FnT , typename T = typename llvm::function_traits<FnT>::template arg_t<0>> void mlir::TypeConverter::addConversion (FnT && callback) inline
Register a conversion function.
A conversion function must be convertible to any of the following forms(where T is a class derived from Type:
Optional<Type>(T)
This form represents a 1-1 type conversion. It should return nullptr or llvm::None to signify failure. If llvm::None is returned, the converter is allowed to try another conversion function to perform the conversion.
Optional<LogicalResult>(T, SmallVectorImpl<Type> &)
This form represents a 1-N type conversion. It should return failure or llvm::None to signify a failed conversion. If the new set of types is empty, the type is removed and any usages of the existing value are expected to be removed during conversion. If llvm::None is returned, the converter is allowed to try another conversion function to perform the conversion. Note: When attempting to convert a type, e.g. via 'convertType', the mostly recently added conversions will be invoked first.
Definition at line 112 of file DialectConversion.h.
References convertBlockSignature(), convertSignatureArg(), convertType(), convertTypes(), mlir::TypeConverter::SignatureConversion::InputMapping::inputNo, isLegal(), and isSignatureLegal().
Referenced by mlir::LLVMTypeConverter::LLVMTypeConverter(), mlir::populateLinalgToLLVMConversionPatterns(), and mlir::SPIRVTypeConverter::SPIRVTypeConverter().
convertBlockSignature()
auto TypeConverter::convertBlockSignature (Block * block)
This function converts the type signature of the given block, by invoking 'convertSignatureArg' for each argument.
This function should return a valid conversion for the signature on success, None otherwise.
Definition at line 1805 of file DialectConversion.cpp.
References mlir::failed(), mlir::Block::getArgument(), mlir::Block::getNumArguments(), mlir::BlockArgument::getType(), and mlir::StandardTypes::None.
Referenced by addConversion().
convertSignatureArg()
LogicalResult TypeConverter::convertSignatureArg (unsigned inputNo, Type type, SignatureConversion & result) virtual
This hook allows for converting a specific argument of a signature.
It takes as inputs the original argument input number, type. On success, this function should populate 'result' with any new mappings.
Definition at line 1742 of file DialectConversion.cpp.
References mlir::TypeConverter::SignatureConversion::addInputs(), mlir::ConversionPatternRewriter::applySignatureConversion(), convertSignatureArg(), convertTypes(), mlir::failed(), mlir::failure(), mlir::FunctionType::get(), mlir::OpState::getContext(), mlir::FunctionType::getInput(), mlir::FunctionType::getNumInputs(), mlir::FunctionType::getResults(), mlir::success(), and mlir::PatternRewriter::updateRootInPlace().
Referenced by addConversion(), and convertSignatureArg().
convertType() [1/2]
LogicalResult TypeConverter::convertType (Type t, SmallVectorImpl< Type > & results)
Convert the given type.
This hooks allows for converting a type.
This function should return failure if no valid conversion exists, success otherwise. If the new set of types is empty, the type is removed and any usages of the existing value are expected to be removed during conversion.
Definition at line 1692 of file DialectConversion.cpp.
References mlir::failure().
Referenced by addConversion(), adjustAccessChainForBitwidth(), mlir::barePtrFuncArgTypeConverter(), mlir::LLVMTypeConverter::convertFunctionTypeCWrapper(), convertMemRefTypeToBarePtr(), convertRangeType(), extractNDVectorTypeInfo(), extractOne(), mlir::MemRefDescriptor::fromStaticShape(), getI64SubArray(), getPtrToElementType(), insertOne(), lowerAsEntryFunction(), mlir::GPUFuncOpLowering< AllocaAddrSpace >::matchAndRewrite(), mlir::OpToFuncCallLowering< SourceOp >::matchAndRewrite(), matchAndRewriteOneToOne(), matchSimpleAtomicOp(), mlir::LLVM::detail::oneToOneRewrite(), mlir::MemRefDescriptor::pack(), mlir::UnrankedMemRefDescriptor::pack(), mlir::structFuncArgTypeConverter(), mlir::LLVM::detail::vectorOneToOneRewrite(), and wrapExternalFunction().
convertType() [2/2]
Type TypeConverter::convertType (Type t)
This hook simplifies defining 1-1 type conversions.
This function returns the type to convert to on success, and a null type on failure.
Definition at line 1704 of file DialectConversion.cpp.
References mlir::failed().
convertTypes()
LogicalResult TypeConverter::convertTypes (ArrayRef< Type > types, SmallVectorImpl< Type > & results)
Convert the given set of types, filling 'results' as necessary.
This returns failure if the conversion of any of the types fails, success otherwise.
Definition at line 1717 of file DialectConversion.cpp.
References mlir::failed(), mlir::failure(), and mlir::success().
Referenced by addConversion(), and convertSignatureArg().
isLegal()
bool TypeConverter::isLegal (Type type)
Return true if the given type is legal for this type converter, i.e.
the type converts to itself.
Definition at line 1727 of file DialectConversion.cpp.
References mlir::succeeded().
Referenced by addConversion(), and mlir::ConversionTarget::addIllegalDialect().
isSignatureLegal()
bool TypeConverter::isSignatureLegal (FunctionType funcType)
Return true if the inputs and outputs of the given function type are legal.
Definition at line 1735 of file DialectConversion.cpp.
References mlir::FunctionType::getInputs(), and mlir::FunctionType::getResults().
Referenced by addConversion(), mlir::populateAVX512ToLLVMConversionPatterns(), mlir::populateLinalgToLLVMConversionPatterns(), and mlir::populateVectorToLLVMMatrixConversionPatterns().
materializeConversion()
virtual Operation* mlir::TypeConverter::materializeConversion (PatternRewriter & rewriter, Type resultType, ArrayRef< Value > inputs, Location loc) inline virtual
This hook allows for materializing a conversion from a set of types into one result type by generating a cast operation of some kind.
The generated operation should produce one result, of 'resultType', with the provided 'inputs' as operands. This hook must be overridden when a type conversion results in more than one type, or if a type conversion may persist after the conversion has finished.
Reimplemented in mlir::LLVMTypeConverter.
Definition at line 157 of file DialectConversion.h.
References mlir::Type::dyn_cast(), mlir::StandardTypes::None, mlir::success(), and mlir::StandardAttributes::Type.
The documentation for this class was generated from the following files:
include/mlir/Transforms/DialectConversion.h
lib/Transforms/DialectConversion.cpp