MLIR: lib/Conversion/AVX512ToLLVM/ConvertAVX512ToLLVM.cpp File Reference
ConvertAVX512ToLLVM.cpp File Reference
#include "mlir/Conversion/AVX512ToLLVM/ConvertAVX512ToLLVM.h"
#include "../PassDetail.h"
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVM.h"
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVMPass.h"
#include "mlir/Conversion/VectorToLLVM/ConvertVectorToLLVM.h"
#include "mlir/Dialect/AVX512/AVX512Dialect.h"
#include "mlir/Dialect/LLVMIR/LLVMAVX512Dialect.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/IR/Module.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Pass/Pass.h"
Functions
template<typename OpTy >
static Type getSrcVectorElementType (OpTy op)
template<typename SourceOp , typename TargetOp >
static LogicalResult matchAndRewriteOneToOne (const ConvertToLLVMPattern &lowering, LLVMTypeConverter &typeConverter, Operation *op, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter)
Basic lowering implementation for one-to-one rewriting from AVX512 Ops to LLVM Dialect Ops.
Function Documentation
getSrcVectorElementType()
template<typename OpTy > static Type getSrcVectorElementType (OpTy op) static
Definition at line 29 of file ConvertAVX512ToLLVM.cpp.
References getElementType().
Referenced by matchAndRewriteOneToOne().
matchAndRewriteOneToOne()
template<typename SourceOp , typename TargetOp > static LogicalResult matchAndRewriteOneToOne (const ConvertToLLVMPattern & lowering, LLVMTypeConverter & typeConverter, Operation * op, ArrayRef< Value > operands, ConversionPatternRewriter & rewriter) static
Basic lowering implementation for one-to-one rewriting from AVX512 Ops to LLVM Dialect Ops.
Convert the type of the result to an LLVM type, pass operands as is, preserve attributes.
Definition at line 41 of file ConvertAVX512ToLLVM.cpp.
References mlir::TypeConverter::convertType(), mlir::PatternRewriter::create(), mlir::ConversionPatternRewriter::eraseOp(), mlir::failure(), mlir::Operation::getAttrs(), mlir::Builder::getI64ArrayAttr(), mlir::Operation::getLoc(), mlir::Operation::getNumResults(), mlir::Operation::getResult(), mlir::Operation::getResultTypes(), getSrcVectorElementType(), mlir::Value::getType(), mlir::LLVMTypeConverter::packFunctionResults(), mlir::ConversionPatternRewriter::replaceOp(), and mlir::success().