MLIR: lib/Dialect/Affine/EDSC/Builders.cpp File Reference
Builders.cpp File Reference
#include "mlir/Dialect/Affine/EDSC/Builders.h"
#include "mlir/Dialect/StandardOps/EDSC/Builders.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
Functions
static Optional< Value > emitStaticFor (ArrayRef< Value > lbs, ArrayRef< Value > ubs, int64_t step)
static std::pair< AffineExpr, Value > categorizeValueByAffineType (MLIRContext *context, Value val, unsigned &numDims, unsigned &numSymbols)
static Value createBinaryIndexHandle (Value lhs, Value rhs, function_ref< AffineExpr(AffineExpr, AffineExpr)> affCombiner)
template<typename IOp , typename FOp >
static Value createBinaryHandle (Value lhs, Value rhs, function_ref< AffineExpr(AffineExpr, AffineExpr)> affCombiner)
static Value createIComparisonExpr (CmpIPredicate predicate, Value lhs, Value rhs)
static Value createFComparisonExpr (CmpFPredicate predicate, Value lhs, Value rhs)
Function Documentation
categorizeValueByAffineType()
static std::pair<AffineExpr, Value> categorizeValueByAffineType (MLIRContext * context, Value val, unsigned & numDims, unsigned & numSymbols) static
Definition at line 92 of file Builders.cpp.
References mlir::getAffineConstantExpr(), mlir::getAffineDimExpr(), mlir::getAffineSymbolExpr(), mlir::Value::getDefiningOp(), mlir::isValidDim(), and mlir::isValidSymbol().
Referenced by createBinaryIndexHandle().
createBinaryHandle()
template<typename IOp , typename FOp > static Value createBinaryHandle (Value lhs, Value rhs, function_ref< AffineExpr(AffineExpr, AffineExpr)> affCombiner) static
Definition at line 136 of file Builders.cpp.
References createBinaryIndexHandle(), and mlir::Value::getType().
createBinaryIndexHandle()
static Value createBinaryIndexHandle (Value lhs, Value rhs, function_ref< AffineExpr(AffineExpr, AffineExpr)> affCombiner) static
Definition at line 108 of file Builders.cpp.
References categorizeValueByAffineType(), mlir::AffineMap::get(), mlir::edsc::ScopedContext::getBuilderRef(), mlir::edsc::ScopedContext::getContext(), mlir::edsc::ScopedContext::getLocation(), mlir::Operation::getNumResults(), mlir::Operation::getResult(), and mlir::makeComposedAffineApply().
Referenced by mlir::edsc::op::ceilDiv(), createBinaryHandle(), and mlir::edsc::op::floorDiv().
createFComparisonExpr()
static Value createFComparisonExpr (CmpFPredicate predicate, Value lhs, Value rhs) static
Definition at line 228 of file Builders.cpp.
References mlir::OpBuilder::create(), mlir::edsc::ScopedContext::getBuilderRef(), mlir::edsc::ScopedContext::getLocation(), and mlir::Value::getType().
Referenced by mlir::edsc::op::eq(), mlir::edsc::op::ne(), mlir::edsc::op::operator<(), mlir::edsc::op::operator<=(), mlir::edsc::op::operator>(), and mlir::edsc::op::operator>=().
createIComparisonExpr()
static Value createIComparisonExpr (CmpIPredicate predicate, Value lhs, Value rhs) static
Definition at line 214 of file Builders.cpp.
References mlir::OpBuilder::create(), mlir::edsc::ScopedContext::getBuilderRef(), mlir::edsc::ScopedContext::getLocation(), and mlir::Value::getType().
Referenced by mlir::edsc::op::eq(), mlir::edsc::op::ne(), mlir::edsc::op::operator<(), mlir::edsc::op::operator<=(), mlir::edsc::op::operator>(), and mlir::edsc::op::operator>=().
emitStaticFor()
static Optional<Value> emitStaticFor (ArrayRef< Value > lbs, ArrayRef< Value > ubs, int64_t step) static
Definition at line 17 of file Builders.cpp.
References mlir::OpBuilder::create(), mlir::edsc::ScopedContext::getBuilderRef(), and mlir::edsc::ScopedContext::getLocation().
Referenced by mlir::edsc::makeAffineLoopBuilder().