MLIR: lib/Transforms/LoopInvariantCodeMotion.cpp File Reference
LoopInvariantCodeMotion.cpp File Reference
#include "PassDetail.h"
#include "mlir/Transforms/Passes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/Function.h"
#include "mlir/Interfaces/LoopLikeInterface.h"
#include "mlir/Interfaces/SideEffects.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "licm"
Functions
static bool canBeHoisted (Operation *op, function_ref< bool(Value)> definedOutside)
static LogicalResult moveLoopInvariantCode (LoopLikeOpInterface looplike)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "licm"
Definition at line 24 of file LoopInvariantCodeMotion.cpp.
Function Documentation
canBeHoisted()
static bool canBeHoisted (Operation * op, function_ref< bool(Value)> definedOutside) static
Definition at line 41 of file LoopInvariantCodeMotion.cpp.
References mlir::Operation::getOperands(), mlir::Operation::getRegions(), and mlir::Operation::hasTrait().
Referenced by moveLoopInvariantCode().
moveLoopInvariantCode()
static LogicalResult moveLoopInvariantCode (LoopLikeOpInterface looplike) static
Definition at line 76 of file LoopInvariantCodeMotion.cpp.
References canBeHoisted(), mlir::failed(), mlir::LoopLikeOpInterface::getLoopBody(), mlir::LoopLikeOpInterface::isDefinedOutsideOfLoop(), mlir::LoopLikeOpInterface::moveOutOfLoop(), and mlir::OpState::print().