MLIR: lib/Conversion/LoopsToGPU/LoopsToGPU.cpp File Reference
LoopsToGPU.cpp File Reference
#include "mlir/Conversion/LoopsToGPU/LoopsToGPU.h"
#include "mlir/Conversion/AffineToStandard/AffineToStandard.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/GPU/GPUDialect.h"
#include "mlir/Dialect/GPU/ParallelLoopMapper.h"
#include "mlir/Dialect/LoopOps/LoopOps.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/Builders.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/LoopUtils.h"
#include "mlir/Transforms/Passes.h"
#include "mlir/Transforms/RegionUtils.h"
#include "llvm/ADT/Sequence.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "loops-to-gpu"
Functions
static Value getDim3Value (const gpu::KernelDim3 &dim3, unsigned pos)
static Operation::operand_range getLowerBoundOperands (AffineForOp forOp)
static SmallVector< Value, 1 > getLowerBoundOperands (ForOp forOp)
static Operation::operand_range getUpperBoundOperands (AffineForOp forOp)
static SmallVector< Value, 1 > getUpperBoundOperands (ForOp forOp)
static Value getOrCreateStep (AffineForOp forOp, OpBuilder &builder)
static Value getOrCreateStep (ForOp forOp, OpBuilder &)
static Value getOrEmitLowerBound (AffineForOp forOp, OpBuilder &builder)
static Value getOrEmitLowerBound (ForOp forOp, OpBuilder &)
static Value getOrEmitUpperBound (AffineForOp forOp, OpBuilder &builder)
static Value getOrEmitUpperBound (ForOp forOp, OpBuilder &)
template<typename OpTy >
static LogicalResult checkLoopNestMappableImpl (OpTy forOp, unsigned numDims)
template<typename OpTy >
static LogicalResult checkLoopNestMappable (OpTy forOp, unsigned numBlockDims, unsigned numThreadDims)
template<typename OpTy >
static LogicalResult checkLoopOpMappable (OpTy forOp, unsigned numBlockDims, unsigned numThreadDims)
static bool isConstantOne (Value value)
template<typename OpTy >
static OpTy createGPULaunchLoops (OpTy rootForOp, ArrayRef< Value > ids, ArrayRef< Value > nids)
Given nDims perfectly nested loops rooted as rootForOp, convert them o be partitioned across workgroups or workitems.
static void packIdAndNumId (gpu::KernelDim3 kernelIds, gpu::KernelDim3 kernelNids, unsigned nDims, SmallVectorImpl< Value > &ids, SmallVectorImpl< Value > &nids)
Utility method to convert the gpu::KernelDim3 object for representing id of each workgroup/workitem and number of workgroup/workitems along a dimension of the launch into a container.
template<typename OpTy >
static LogicalResult createLaunchBody (OpBuilder &builder, OpTy rootForOp, gpu::LaunchOp launchOp, unsigned numBlockDims, unsigned numThreadDims)
Generate the body of the launch operation.
template<typename OpTy >
static LogicalResult createLaunchFromOp (OpTy rootForOp, ArrayRef< Value > numWorkGroups, ArrayRef< Value > workGroupSizes)
template<typename OpTy >
static LogicalResult convertLoopNestToGPULaunch (OpTy forOp, unsigned numBlockDims, unsigned numThreadDims)
template<typename OpTy >
static LogicalResult convertLoopToGPULaunch (OpTy forOp, ArrayRef< Value > numWorkGroups, ArrayRef< Value > workGroupSize)
static Value deriveStaticUpperBound (Value upperBound, PatternRewriter &rewriter)
Tries to derive a static upper bound from the defining operation of upperBound.
static bool isMappedToProcessor (gpu::Processor processor)
static unsigned getLaunchOpArgumentNum (gpu::Processor processor)
static LogicalResult processParallelLoop (ParallelOp parallelOp, gpu::LaunchOp launchOp, BlockAndValueMapping &cloningMap, SmallVectorImpl< Operation *> &worklist, DenseMap< gpu::Processor, Value > &bounds, PatternRewriter &rewriter)
Modifies the current transformation state to capture the effect of the given loop.parallel operation on index substitutions and the operations to be inserted.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "loops-to-gpu"
Definition at line 34 of file LoopsToGPU.cpp.
Function Documentation
checkLoopNestMappable()
template<typename OpTy > static LogicalResult checkLoopNestMappable (OpTy forOp, unsigned numBlockDims, unsigned numThreadDims) static
Definition at line 132 of file LoopsToGPU.cpp.
References checkLoopNestMappableImpl(), and mlir::success().
Referenced by convertLoopNestToGPULaunch().
checkLoopNestMappableImpl()
template<typename OpTy > static LogicalResult checkLoopNestMappableImpl (OpTy forOp, unsigned numDims) static
Definition at line 106 of file LoopsToGPU.cpp.
References mlir::areValuesDefinedAbove(), mlir::Operation::emitError(), getLowerBoundOperands(), getUpperBoundOperands(), and mlir::success().
Referenced by checkLoopNestMappable(), and checkLoopOpMappable().
checkLoopOpMappable()
template<typename OpTy > static LogicalResult checkLoopOpMappable (OpTy forOp, unsigned numBlockDims, unsigned numThreadDims) static
Definition at line 149 of file LoopsToGPU.cpp.
References checkLoopNestMappableImpl(), mlir::failed(), mlir::failure(), and mlir::success().
Referenced by convertLoopToGPULaunch().
convertLoopNestToGPULaunch()
template<typename OpTy > static LogicalResult convertLoopNestToGPULaunch (OpTy forOp, unsigned numBlockDims, unsigned numThreadDims) static
Definition at line 448 of file LoopsToGPU.cpp.
References checkLoopNestMappable(), mlir::failed(), mlir::failure(), and mlir::success().
Referenced by mlir::convertAffineLoopNestToGPULaunch().
convertLoopToGPULaunch()
template<typename OpTy > static LogicalResult convertLoopToGPULaunch (OpTy forOp, ArrayRef< Value > numWorkGroups, ArrayRef< Value > workGroupSize) static
Definition at line 467 of file LoopsToGPU.cpp.
References checkLoopOpMappable(), createLaunchFromOp(), mlir::failed(), and mlir::failure().
Referenced by mlir::convertLoopToGPULaunch().
createGPULaunchLoops()
template<typename OpTy > static OpTy createGPULaunchLoops (OpTy rootForOp, ArrayRef< Value > ids, ArrayRef< Value > nids) static
Given nDims perfectly nested loops rooted as rootForOp, convert them o be partitioned across workgroups or workitems.
The values for the workgroup/workitem id along each dimension is passed in with ids. The number of workgroups/workitems along each dimension are passed in with nids. The innermost loop is mapped to the x-dimension, followed by the next innermost loop to y-dimension, followed by z-dimension.
Definition at line 272 of file LoopsToGPU.cpp.
References mlir::mapLoopToProcessorIds().
Referenced by createLaunchBody().
createLaunchBody()
template<typename OpTy > static LogicalResult createLaunchBody (OpBuilder & builder, OpTy rootForOp, gpu::LaunchOp launchOp, unsigned numBlockDims, unsigned numThreadDims) static
Generate the body of the launch operation.
Definition at line 309 of file LoopsToGPU.cpp.
References mlir::OpBuilder::create(), createGPULaunchLoops(), packIdAndNumId(), mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointToEnd(), and mlir::success().
Referenced by createLaunchFromOp().
createLaunchFromOp()
template<typename OpTy > static LogicalResult createLaunchFromOp (OpTy rootForOp, ArrayRef< Value > numWorkGroups, ArrayRef< Value > workGroupSizes) static
Definition at line 345 of file LoopsToGPU.cpp.
References createLaunchBody(), mlir::detail::enumerate(), mlir::failed(), mlir::failure(), getDim3Value(), isConstantOne(), mlir::StandardTypes::None, mlir::Value::replaceAllUsesWith(), and mlir::success().
Referenced by convertLoopToGPULaunch().
deriveStaticUpperBound()
static Value deriveStaticUpperBound (Value upperBound, PatternRewriter & rewriter) static
Tries to derive a static upper bound from the defining operation of upperBound.
Definition at line 506 of file LoopsToGPU.cpp.
References mlir::PatternRewriter::create(), and mlir::Value::getDefiningOp().
Referenced by processParallelLoop().
getDim3Value()
static Value getDim3Value (const gpu::KernelDim3 & dim3, unsigned pos) static
Definition at line 42 of file LoopsToGPU.cpp.
References mlir::gpu::KernelDim3::x, mlir::gpu::KernelDim3::y, and mlir::gpu::KernelDim3::z.
Referenced by createLaunchFromOp().
getLaunchOpArgumentNum()
static unsigned getLaunchOpArgumentNum (gpu::Processor processor) static
Definition at line 545 of file LoopsToGPU.cpp.
Referenced by processParallelLoop().
getLowerBoundOperands() [1/2]
static Operation::operand_range getLowerBoundOperands (AffineForOp forOp) static
Definition at line 57 of file LoopsToGPU.cpp.
Referenced by canonicalizeLoopBounds(), and checkLoopNestMappableImpl().
getLowerBoundOperands() [2/2]
static SmallVector<Value, 1> getLowerBoundOperands (ForOp forOp) static
Definition at line 60 of file LoopsToGPU.cpp.
getOrCreateStep() [1/2]
static Value getOrCreateStep (AffineForOp forOp, OpBuilder & builder) static
Definition at line 76 of file LoopsToGPU.cpp.
References mlir::OpBuilder::create().
Referenced by isConstantOne().
getOrCreateStep() [2/2]
static Value getOrCreateStep (ForOp forOp, OpBuilder &) static
Definition at line 79 of file LoopsToGPU.cpp.
getOrEmitLowerBound() [1/2]
static Value getOrEmitLowerBound (AffineForOp forOp, OpBuilder & builder) static
Definition at line 83 of file LoopsToGPU.cpp.
References mlir::lowerAffineLowerBound().
Referenced by isConstantOne().
getOrEmitLowerBound() [2/2]
static Value getOrEmitLowerBound (ForOp forOp, OpBuilder &) static
Definition at line 86 of file LoopsToGPU.cpp.
getOrEmitUpperBound() [1/2]
static Value getOrEmitUpperBound (AffineForOp forOp, OpBuilder & builder) static
Definition at line 92 of file LoopsToGPU.cpp.
References mlir::lowerAffineUpperBound().
Referenced by isConstantOne().
getOrEmitUpperBound() [2/2]
static Value getOrEmitUpperBound (ForOp forOp, OpBuilder &) static
Definition at line 95 of file LoopsToGPU.cpp.
getUpperBoundOperands() [1/2]
static Operation::operand_range getUpperBoundOperands (AffineForOp forOp) static
Definition at line 66 of file LoopsToGPU.cpp.
Referenced by canonicalizeLoopBounds(), and checkLoopNestMappableImpl().
getUpperBoundOperands() [2/2]
static SmallVector<Value, 1> getUpperBoundOperands (ForOp forOp) static
Definition at line 69 of file LoopsToGPU.cpp.
isConstantOne()
static bool isConstantOne (Value value) static
Definition at line 221 of file LoopsToGPU.cpp.
References mlir::Value::getDefiningOp(), getOrCreateStep(), getOrEmitLowerBound(), getOrEmitUpperBound(), and mlir::StandardTypes::None.
Referenced by createLaunchFromOp().
isMappedToProcessor()
static bool isMappedToProcessor (gpu::Processor processor) static
Definition at line 541 of file LoopsToGPU.cpp.
Referenced by processParallelLoop().
packIdAndNumId()
static void packIdAndNumId (gpu::KernelDim3 kernelIds, gpu::KernelDim3 kernelNids, unsigned nDims, SmallVectorImpl< Value > & ids, SmallVectorImpl< Value > & nids) static
Utility method to convert the gpu::KernelDim3 object for representing id of each workgroup/workitem and number of workgroup/workitems along a dimension of the launch into a container.
Definition at line 292 of file LoopsToGPU.cpp.
References mlir::gpu::KernelDim3::x, mlir::gpu::KernelDim3::y, and mlir::gpu::KernelDim3::z.
Referenced by createLaunchBody().
processParallelLoop()
static LogicalResult processParallelLoop (ParallelOp parallelOp, gpu::LaunchOp launchOp, BlockAndValueMapping & cloningMap, SmallVectorImpl< Operation *> & worklist, DenseMap< gpu::Processor, Value > & bounds, PatternRewriter & rewriter) static
Modifies the current transformation state to capture the effect of the given loop.parallel operation on index substitutions and the operations to be inserted.
Specifically, if a dimension of a parallel loop is mapped to a hardware id, this function will
compute the loop index based on the hardware id and affine map from the mapping and update cloningMap to substitute all uses.
derive a new upper bound for the hardware id and augment the provided gpu.launch operation accordingly.
if the upper bound is imprecise, insert a conditional in the gpu.launch and update the rewriter to insert into the conditional's body. If the dimension is mapped to sequential,
insert a for loop into the body and update the rewriter to insert into the for loop's body.
update the cloningMap to replace uses of the index with the index of the new for loop. In either case,
append the instructions from the loops body to worklist, in reverse order. To note the end of the current scope in case a loop or conditional was inserted, a sentinel (the gpu.launch operation) is inserted into the worklist. This signals the processor of the worklist to pop the rewriter one scope-level up.
Definition at line 587 of file LoopsToGPU.cpp.
References mlir::ceilDiv(), mlir::OpBuilder::clone(), mlir::PatternRewriter::create(), deriveStaticUpperBound(), mlir::Attribute::dyn_cast(), mlir::PatternRewriter::eraseOp(), mlir::failed(), mlir::failure(), mlir::AffineMap::get(), mlir::Builder::getAffineDimExpr(), mlir::Builder::getAffineSymbolExpr(), mlir::Value::getDefiningOp(), mlir::OpBuilder::getInsertionPoint(), getLaunchOpArgumentNum(), mlir::gpu::getMappingAttrName(), mlir::Operation::getNumRegions(), mlir::Block::getOperations(), mlir::gpu::getProcessor(), mlir::Operation::getResults(), mlir::MemoryEffectOpInterface::hasNoEffect(), isMappedToProcessor(), mlir::BlockAndValueMapping::lookupOrDefault(), mlir::BlockAndValueMapping::map(), mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointAfter(), mlir::OpBuilder::setInsertionPointToEnd(), mlir::OpBuilder::setInsertionPointToStart(), mlir::success(), and mlir::Block::without_terminator().