MLIR: lib/Dialect/Linalg/Transforms/Loops.cpp File Reference
Loops.cpp File Reference
#include "PassDetail.h"
#include "mlir/Dialect/Affine/EDSC/Intrinsics.h"
#include "mlir/Dialect/Linalg/EDSC/FoldedIntrinsics.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/IR/LinalgTypes.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/LoopOps/EDSC/Builders.h"
#include "mlir/Dialect/StandardOps/EDSC/Intrinsics.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/FoldUtils.h"
#include "mlir/Dialect/Linalg/IR/LinalgStructuredOps.cpp.inc"
Classes
struct InputAndOutputIndices
Macros
#define GET_OP_LIST
#define INSTANTIATE_LINALG_OP_TO_LOOPS(OP_TYPE)
Functions
static SmallVector< Value, 8 > makeCanonicalAffineApplies (OpBuilder &b, Location loc, AffineMap map, ArrayRef< Value > vals)
static SmallVector< Value, 4 > permuteIvs (ArrayRef< Value > ivs, Optional< AffineMap > permutation)
static SmallVector< Value, 4 > emitLoopRanges (OpBuilder &b, Location loc, AffineMap map, ArrayRef< Value > allViewSizes)
template<typename IndexedValueType , typename OpType >
static void inlineRegionAndEmitStore (OpType op, ArrayRef< Value > indexedValues, ArrayRef< SmallVector< Value, 8 >> indexing, ArrayRef< Value > outputBuffers)
template<typename SingleInputPoolingOp >
static InputAndOutputIndices getInputAndOutputIndices (ArrayRef< Value > allIvs, SingleInputPoolingOp op)
template<typename LoopType >
static void lowerLinalgToLoopsImpl (Operation *op, MLIRContext *context)
Macro Definition Documentation
GET_OP_LIST
#define GET_OP_LIST
INSTANTIATE_LINALG_OP_TO_LOOPS
#define INSTANTIATE_LINALG_OP_TO_LOOPS (OP_TYPE)
Value:
template LogicalResult mlir::linalg::linalgOpToLoops<OP_TYPE>(\
      OpBuilder & builder, Operation * op);                                    \
  template LogicalResult mlir::linalg::linalgOpToAffineLoops<OP_TYPE>(         \
      OpBuilder & builder, Operation * op);                                    \
  template LogicalResult mlir::linalg::linalgOpToParallelLoops<OP_TYPE>(       \
      OpBuilder & builder, Operation * op);                                    \
  template Optional<LinalgLoops>                                               \
      mlir::linalg::linalgLowerOpToLoops<loop::ParallelOp, OP_TYPE>(           \
          OpBuilder & builder, Operation * op);
Definition at line 778 of file Loops.cpp.
Function Documentation
emitLoopRanges()
SmallVector< Value, 4 > emitLoopRanges (OpBuilder & b, Location loc, AffineMap map, ArrayRef< Value > allViewSizes) static
Definition at line 67 of file Loops.cpp.
References mlir::linalg::applyMapToValues(), and mlir::AffineMap::getNumResults().
Referenced by getInputAndOutputIndices(), and permuteIvs().
getInputAndOutputIndices()
template<typename SingleInputPoolingOp > static InputAndOutputIndices getInputAndOutputIndices (ArrayRef< Value > allIvs, SingleInputPoolingOp op) static
Definition at line 111 of file Loops.cpp.
References mlir::Attribute::cast(), mlir::Type::cast(), mlir::concatAffineMaps(), mlir::AffineExpr::dyn_cast(), mlir::Value::dyn_cast(), emitLoopRanges(), mlir::detail::enumerate(), mlir::PatternRewriter::eraseOp(), mlir::failure(), mlir::AffineMap::get(), mlir::getAffineConstantExpr(), mlir::getAffineDimExpr(), mlir::edsc::ScopedContext::getBuilderRef(), mlir::edsc::ScopedContext::getContext(), getElementType(), mlir::Operation::getLoc(), mlir::edsc::ScopedContext::getLocation(), mlir::Operation::getOperand(), mlir::BlockArgument::getOwner(), mlir::getParallelIteratorTypeName(), mlir::Block::getParentOp(), mlir::AffineMapAttr::getValue(), mlir::linalg::getViewSizes(), mlir::Builder::getZeroAttr(), mlir::OwningRewritePatternList::insert(), mlir::inversePermutation(), mlir::AffineMap::isEmpty(), makeCanonicalAffineApplies(), permuteIvs(), mlir::PatternRewriter::replaceOp(), mlir::PatternRewriter::replaceOpWithNewOp(), and mlir::success().
inlineRegionAndEmitStore()
template<typename IndexedValueType , typename OpType > static void inlineRegionAndEmitStore (OpType op, ArrayRef< Value > indexedValues, ArrayRef< SmallVector< Value, 8 >> indexing, ArrayRef< Value > outputBuffers) static
Definition at line 82 of file Loops.cpp.
References mlir::OpBuilder::clone(), mlir::edsc::ScopedContext::getBuilderRef(), mlir::Operation::getNumOperands(), mlir::Operation::getOperand(), mlir::BlockAndValueMapping::lookupOrDefault(), and mlir::BlockAndValueMapping::map().
lowerLinalgToLoopsImpl()
template<typename LoopType > static void lowerLinalgToLoopsImpl (Operation * op, MLIRContext * context) static
Definition at line 696 of file Loops.cpp.
References mlir::applyPatternsAndFoldGreedily().
makeCanonicalAffineApplies()
static SmallVector<Value, 8> makeCanonicalAffineApplies (OpBuilder & b, Location loc, AffineMap map, ArrayRef< Value > vals) static
Definition at line 33 of file Loops.cpp.
References mlir::canonicalizeMapAndOperands(), mlir::AffineMap::get(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumInputs(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::AffineMap::getResults(), and mlir::AffineMap::isEmpty().
Referenced by getInputAndOutputIndices().
permuteIvs()
static SmallVector<Value, 4> permuteIvs (ArrayRef< Value > ivs, Optional< AffineMap > permutation) static
Definition at line 53 of file Loops.cpp.
References mlir::linalg::applyMapToValues(), emitLoopRanges(), mlir::edsc::ScopedContext::getBuilderRef(), and mlir::edsc::ScopedContext::getLocation().
Referenced by getInputAndOutputIndices().