MLIR: impl Namespace Reference
impl Namespace Reference
Classes
struct MemRefDataPrinter
struct MemRefDataPrinter< T, 0 >
struct StaticSizeMult
struct StaticSizeMult< N, Dims... >
struct VectorDataPrinter
Functions
template<typename T , int M, int... Dims>
std::ostream & operator<< (std::ostream &os, const Vector< T, M, Dims... > &v)
static void printSpace (std::ostream &os, int count)
template<typename T , int N>
void printMemRef (StridedMemRefType< T, N > &M)
template<typename T >
void printMemRef (StridedMemRefType< T, 0 > &M)
Function Documentation
operator<<()
template<typename T , int M, int... Dims> std::ostream & impl::operator<< (std::ostream & os, const Vector< T, M, Dims... > & v)
Definition at line 116 of file RunnerUtils.h.
References impl::VectorDataPrinter< T, M, Dims >::print().
printMemRef() [1/2]
template<typename T , int N> void impl::printMemRef (StridedMemRefType< T, N > & M)
Definition at line 188 of file RunnerUtils.h.
References StridedMemRefType< T, N >::data, StridedMemRefType< T, N >::offset, impl::MemRefDataPrinter< T, N >::print(), printMemRefMetaData(), StridedMemRefType< T, N >::sizes, and StridedMemRefType< T, N >::strides.
Referenced by _mlir_ciface_print_memref_0d_f32(), _mlir_ciface_print_memref_1d_f32(), _mlir_ciface_print_memref_2d_f32(), _mlir_ciface_print_memref_3d_f32(), _mlir_ciface_print_memref_4d_f32(), and _mlir_ciface_print_memref_vector_4x4xf32().
printMemRef() [2/2]
template<typename T > void impl::printMemRef (StridedMemRefType< T, 0 > & M)
Definition at line 197 of file RunnerUtils.h.
References _mlir_ciface_print_memref_0d_f32(), _mlir_ciface_print_memref_1d_f32(), _mlir_ciface_print_memref_2d_f32(), _mlir_ciface_print_memref_3d_f32(), _mlir_ciface_print_memref_4d_f32(), _mlir_ciface_print_memref_f32(), _mlir_ciface_print_memref_i8(), _mlir_ciface_print_memref_vector_4x4xf32(), StridedMemRefType< T, 0 >::data, MLIR_RUNNERUTILS_EXPORT, StridedMemRefType< T, 0 >::offset, impl::MemRefDataPrinter< T, N >::print(), print_memref_f32(), print_memref_i32(), and printMemRefMetaData().
printSpace()
static void impl::printSpace (std::ostream & os, int count) inline static
Definition at line 78 of file RunnerUtils.h.
Referenced by impl::VectorDataPrinter< T, M, Dims >::print(), impl::MemRefDataPrinter< T, N >::print(), and impl::MemRefDataPrinter< T, N >::printLast().