MLIR: mlir::loop Namespace Reference
mlir::loop Namespace Reference
Functions
void ensureLoopTerminator (Region &region, Builder &builder, Location loc)
ForOp getForInductionVarOwner (Value val)
Returns the loop parent of an induction variable.
ParallelOp getParallelForInductionVarOwner (Value val)
Returns the parallel loop parent of an induction variable. If the provided.
void naivelyFuseParallelOps (Region &region)
Fuses all adjacent loop.parallel operations with identical bounds and step into one loop.parallel operations.
void tileParallelLoop (ParallelOp op, llvm::ArrayRef< int64_t > tileSizes)
Tile a parallel loop of the form loop.parallel (i0, i1) = (arg0, arg1) to (arg2, arg3) step (arg4, arg5)
Function Documentation
ensureLoopTerminator()
void mlir::loop::ensureLoopTerminator (Region & region, Builder & builder, Location loc)
getForInductionVarOwner()
ForOp mlir::loop::getForInductionVarOwner (Value val)
Returns the loop parent of an induction variable.
If the provided value is not an induction variable, then return nullptr.
Referenced by getBackwardSliceImpl(), mlir::edsc::makeLoopBuilder(), and parseForOp().
getParallelForInductionVarOwner()
ParallelOp mlir::loop::getParallelForInductionVarOwner (Value val)
Returns the parallel loop parent of an induction variable. If the provided.
Definition at line 545 of file LoopOps.cpp.
References mlir::Block::addArguments(), mlir::OperationState::addOperands(), mlir::OperationState::addRegion(), mlir::Value::dyn_cast(), mlir::Region::end(), mlir::Region::getBlocks(), and mlir::Value::getType().
naivelyFuseParallelOps()
void mlir::loop::naivelyFuseParallelOps (Region & region)
Fuses all adjacent loop.parallel operations with identical bounds and step into one loop.parallel operations.
Uses a naive aliasing and dependency analysis.
Definition at line 131 of file ParallelLoopFusion.cpp.
References fuseIfLegal(), and mlir::MemoryEffectOpInterface::hasNoEffect().
tileParallelLoop()
void mlir::loop::tileParallelLoop (ParallelOp op, llvm::ArrayRef< int64_t > tileSizes)
Tile a parallel loop of the form loop.parallel (i0, i1) = (arg0, arg1) to (arg2, arg3) step (arg4, arg5)
into loop.parallel (i0, i1) = (arg0, arg1) to (arg2, arg3) step (arg4*tileSize[0], arg5*tileSize[1]) loop.parallel (j0, j1) = (0, 0) to (min(tileSize[0], arg2-j0) min(tileSize[1], arg3-j1)) step (arg4, arg5) The old loop is replaced with the new one.
Definition at line 37 of file ParallelLoopTiling.cpp.
References mlir::OpBuilder::create(), mlir::AffineMap::get(), mlir::getAffineDimExpr(), mlir::Builder::getContext(), mlir::Builder::getIndexType(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by getInnermostNestedLoops().