MLIR: mlir::linalg Namespace Reference
mlir::linalg Namespace Reference
Classes
class Aliases
A very primitive alias analysis which just records for each view, either:
struct FusionInfo
struct LinalgBaseInterchangePattern
Linalg interchange patterns.
struct LinalgBasePromotionPattern
Linalg promotion patterns.
struct LinalgBaseTilingPattern
struct LinalgBaseVectorizationPattern
Linalg vectorization patterns.
class LinalgDependenceGraph
Data structure for holding a dependence graph that operates on LinalgOp and views as SSA values.
struct LinalgInterchangePattern
struct LinalgLoweringPattern
struct LinalgMarker
Helper class to control common attribute matching and setting behavior.
struct LinalgPromotionPattern
struct LinalgTilingOptions
struct LinalgTilingPattern
struct LinalgTransforms
struct LinalgVectorizationPattern
struct PromotionInfo
class RangeType
A RangeType represents a minimal range abstraction (min, max, step).
struct RegionMatcher
A struct containing common matchers over linalg op's region.
struct TiledLinalgOp
Typedefs
using LinalgLoops = SmallVector< Operation *, 4 >
Enumerations
enum LinalgTypes { Range = Type::FIRST_LINALG_TYPE, LAST_USED_LINALG_TYPE = Range }
enum LinalgTilingLoopType { LinalgTilingLoopType::Loops = 0, LinalgTilingLoopType::AffineLoops = 1, LinalgTilingLoopType::ParallelLoops = 2 }
Linalg tiling patterns.
enum LinalgLoweringType { LinalgLoweringType::LibraryCall = 0, LinalgLoweringType::Loops = 1, LinalgLoweringType::AffineLoops = 2, LinalgLoweringType::ParallelLoops = 3 }
Linalg lowering patterns.
Functions
std::string generateLibraryCallName (Operation *op)
Returns the name mangled library call name to disambiguate between different overloads at the C level.
SmallVector< AffineExpr, 4 > makeAffineDimExprs (unsigned num, unsigned &startIdx, MLIRContext *context)
Returns num AffineDimExpr dimensions at positions [startIdx, startIdx + num) and increments startIdx to startIdx + num.
template<typename PoolingOp >
SmallVector< AffineExpr, 4 > weightedPoolingInputIndex (PoolingOp op, ArrayRef< AffineExpr > outputDims, ArrayRef< AffineExpr > windowDims)
Builds the indexing expressions for a ConvOp/PoolingOp op.
AffineMap extractOrIdentityMap (Optional< AffineMap > maybeMap, unsigned rank, MLIRContext *context)
Returns maybeMap.get() if maybeMap is set, otherwise returns the symbol-less identity map of rank.
SmallVector< AffineExpr, 4 > concat (ArrayRef< AffineExpr > a, ArrayRef< AffineExpr > b)
Return the vector that is the concatenation of a and b.
Optional< TiledLinalgOp > tileLinalgOp (OpBuilder &b, LinalgOp op, ArrayRef< Value > tileSizes, ArrayRef< unsigned > interchangeVector={}, OperationFolder *folder=nullptr)
Performs standalone tiling of a single LinalgOp by tileSizes.
Optional< TiledLinalgOp > tileLinalgOpToParallelLoops (OpBuilder &b, LinalgOp op, ArrayRef< Value > tileSizes, ArrayRef< unsigned > interchangeVector={}, OperationFolder *folder=nullptr)
Optional< TiledLinalgOp > tileLinalgOp (OpBuilder &b, LinalgOp op, ArrayRef< int64_t > tileSizes, ArrayRef< unsigned > interchangeVector={}, OperationFolder *folder=nullptr)
Performs standalone tiling of a single LinalgOp by constant tileSizes.
Optional< TiledLinalgOp > tileLinalgOpToParallelLoops (OpBuilder &b, LinalgOp op, ArrayRef< int64_t > tileSizes, ArrayRef< unsigned > interchangeVector={}, OperationFolder *folder=nullptr)
LinalgOp interchange (LinalgOp op, ArrayRef< unsigned > interchangeVector)
Interchanges the iterator_types and iterator_maps dimensions of op.
LinalgOp promoteSubViewOperands (OpBuilder &b, LinalgOp op, llvm::SetVector< Value > subViews, bool dynamicBuffers=false, int64_t alignment=0, OperationFolder *folder=nullptr)
Promotes the subViews into a new buffer allocated at the insertion point b.
void vectorizeLinalgOp (OpBuilder &builder, Operation *op)
Emit a suitable vector form for a Linalg op with fully static shape.
template<typename LoopTy , typename ConcreteOp >
Optional< LinalgLoops > linalgLowerOpToLoops (OpBuilder &builder, Operation *op)
Emits a loop nest of LoopTy with the proper body for op.
template<typename ConcreteOp >
LogicalResult linalgOpToLoops (OpBuilder &builder, Operation *op)
Emits a loop nest of loop.for with the proper body for op.
template<typename ConcreteOp >
LogicalResult linalgOpToParallelLoops (OpBuilder &builder, Operation *op)
Emits a loop nest of loop.parallel with the proper body for op.
template<typename ConcreteOp >
LogicalResult linalgOpToAffineLoops (OpBuilder &builder, Operation *op)
Emits a loop nest of affine.for with the proper body for op.
LogicalResult interchangeGenericLinalgOpPrecondition (Operation *op, ArrayRef< unsigned > interchangeVector)
Emits a generic or indexed_generic operation with the indexing_maps and iterator_types permutated according to permutation.
LogicalResult promoteSubviewsLinalgOpPrecondition (Operation *op, Optional< DenseSet< unsigned >> operandIndicesToPromote=None)
Promote std.subviews feeding linalg operations.
LogicalResult vectorizeLinalgOpPrecondition (Operation *op)
Rewrite a linalg.generic into a suitable vector.contraction op.
bool isProducerLastWriteOfView (const LinalgDependenceGraph &graph, LinalgOp consumer, Value consumedView, LinalgOp producer)
Checks whether the specific producer is the last write to exactly the whole consumedView.
bool isFusableInto (const LinalgDependenceGraph &graph, LinalgOp consumer, Value consumedView, LinalgOp producer)
Checks whether fusing the specific producer of the consumedView is feasible.
Optional< FusionInfo > fuseProducerOf (OpBuilder &b, LinalgOp consumer, unsigned consumerIdx, const LinalgDependenceGraph &graph, OperationFolder *folder=nullptr)
Fuses producer into consumer if the producer is structurally feasible and the fusion would not violate dependencies.
Operation * fuseTensorOps (PatternRewriter &rewriter, Operation *consumer, unsigned consumerIdx, OperationFolder *folder=nullptr)
Fuse linalg operation on tensors, with the producer of the operand at position consumerIdx of the consumer.
template<typename ConcreteOp >
SmallVector< Value, 8 > getViewSizes (OpBuilder &builder, ConcreteOp linalgOp)
Returns the linearized list of all view dimensions in a linalgOp.
SmallVector< Value, 4 > applyMapToValues (OpBuilder &b, Location loc, AffineMap map, ArrayRef< Value > values, OperationFolder *folder=nullptr)
Returns the values obtained by applying map to the list of values.
SmallVector< PromotionInfo, 8 > promoteSubViews (OpBuilder &b, Location loc, ArrayRef< Value > subViews, bool dynamicBuffers=false, int64_t alignment=0, OperationFolder *folder=nullptr)
Promotes the subViews into a new buffer allocated at the insertion point b.
SmallVector< Value, 4 > getAssumedNonViewOperands (LinalgOp linalgOp)
Returns all the operands of linalgOp that are not views.
template<typename T , unsigned N>
void applyPermutationToVector (SmallVector< T, N > &inVec, ArrayRef< unsigned > permutation)
Apply the permutation defined by permutation to inVec.
Typedef Documentation
LinalgLoops
using mlir::linalg::LinalgLoops = typedef SmallVector<Operation *, 4>
Definition at line 21 of file Transforms.h.
Enumeration Type Documentation
LinalgLoweringType
enum mlir::linalg::LinalgLoweringType strong
Linalg lowering patterns.
Apply the linalgLowerOpToLoops transformation as a pattern. marker controls LinalgTransformMarker matching and update when specified. See linalgLowerOpToLoops for more details.
Enumerator
LibraryCall
Loops
AffineLoops
ParallelLoops
Definition at line 324 of file Transforms.h.
LinalgTilingLoopType
enum mlir::linalg::LinalgTilingLoopType strong
Linalg tiling patterns.
Apply the tileLinalgOp transformation as a pattern. marker controls LinalgTransformMarker matching and update when specified. See tileLinalgOp for more details.
Enumerator
Loops
AffineLoops
ParallelLoops
Definition at line 161 of file Transforms.h.
LinalgTypes
enum mlir::linalg::LinalgTypes
Enumerator
Range
LAST_USED_LINALG_TYPE
Definition at line 19 of file LinalgTypes.h.
Function Documentation
applyMapToValues()
SmallVector< Value, 4 > mlir::linalg::applyMapToValues (OpBuilder & b, Location loc, AffineMap map, ArrayRef< Value > values, OperationFolder * folder = nullptr)
Returns the values obtained by applying map to the list of values.
When non-null, the optional pointer folder is used to call into the createAndFold builder method. If folder is null, the regular create method is called.
Definition at line 68 of file Utils.cpp.
References emitOrFoldComposedAffineApply(), mlir::AffineMap::get(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumResults(), and mlir::AffineMap::getResults().
Referenced by emitLoopRanges(), getViewSizes(), makeTiledLoopRanges(), makeTiledViews(), permuteIvs(), and tileLinalgOpImpl().
applyPermutationToVector()
template<typename T , unsigned N> void mlir::linalg::applyPermutationToVector (SmallVector< T, N > & inVec, ArrayRef< unsigned > permutation)
Apply the permutation defined by permutation to inVec.
Element i in inVec is mapped to location j = permutation[i]. E.g.: for an input vector `inVec = ['a', 'b', 'c']and a permutation vector permutation = [2, 0, 1], this function leavesinVec = ['c', 'a', 'b']`.
Definition at line 136 of file Utils.h.
Referenced by interchange(), and tileLinalgOpImpl().
concat()
SmallVector< AffineExpr, 4 > mlir::linalg::concat (ArrayRef< AffineExpr > a, ArrayRef< AffineExpr > b)
Return the vector that is the concatenation of a and b.
Definition at line 976 of file LinalgOps.cpp.
extractOrIdentityMap()
AffineMap mlir::linalg::extractOrIdentityMap (Optional< AffineMap > maybeMap, unsigned rank, MLIRContext * context)
Returns maybeMap.get() if maybeMap is set, otherwise returns the symbol-less identity map of rank.
Definition at line 928 of file LinalgOps.cpp.
References mlir::AffineMap::get(), and mlir::AffineMap::getMultiDimIdentityMap().
fuseProducerOf()
Optional< FusionInfo > mlir::linalg::fuseProducerOf (OpBuilder & b, LinalgOp consumer, unsigned consumerIdx, const LinalgDependenceGraph & graph, OperationFolder * folder = nullptr)
Fuses producer into consumer if the producer is structurally feasible and the fusion would not violate dependencies.
When non-null, the optional pointer folder is used to call into the createAndFold builder method. If folder is null, the regular create method is called.
Definition at line 347 of file Fusion.cpp.
References fuseProducerOfDep(), and mlir::StandardTypes::None.
Referenced by fuseLinalgOpsGreedily().
fuseTensorOps()
Operation * mlir::linalg::fuseTensorOps (PatternRewriter & rewriter, Operation * consumer, unsigned consumerIdx, OperationFolder * folder = nullptr)
Fuse linalg operation on tensors, with the producer of the operand at position consumerIdx of the consumer.
Definition at line 742 of file Fusion.cpp.
References mlir::applyPatternsAndFoldGreedily(), mlir::PatternRewriter::eraseOp(), mlir::failure(), fuse(), fuseLinalgOpsGreedily(), mlir::Operation::getContext(), mlir::Value::getDefiningOp(), mlir::Operation::getNumOperands(), mlir::Operation::getNumResults(), mlir::Operation::getOperand(), mlir::Operation::getRegions(), mlir::Operation::getResults(), mlir::populateLinalgTensorOpsFusionPatterns(), mlir::PatternRewriter::replaceOp(), and mlir::success().
generateLibraryCallName()
std::string mlir::linalg::generateLibraryCallName (Operation * op)
Returns the name mangled library call name to disambiguate between different overloads at the C level.
The name mangling scheme is basic and uses MLIR type names:
form a string which is the concatenation of the linalg op name with all the operand type names, separate by underscores;
drop the linalg. prefix, and the <, >, ? symbols from the type. Assumes op is a LinalgOp.
Examples:
linalg.fill(A, f) : memref<f32>, f32 name mangles into linalg_fill_viewf32_f32_impl
linalg.dot(A, B, C) : memref<?xf32, stride_specification>, memref<?xf32, stride_specification>, memref<f32> name mangles into linalg_dot_viewxf32_viewxf32_viewf32_impl
linalg.matmul(...) : memref<?x?xf32, stride_specification>, memref<?x?xf32, stride_specification>, memref<?x?xf32, stride_specification> name mangles into linalg_matmul_viewxxf32_viewxxf32_viewxxf32_impl
Definition at line 1005 of file LinalgOps.cpp.
References appendMangledType(), foldMemRefCast(), mlir::Operation::getName(), mlir::Operation::getOperandTypes(), mlir::OperationName::getStringRef(), and mlir::succeeded().
getAssumedNonViewOperands()
SmallVector< Value, 4 > mlir::linalg::getAssumedNonViewOperands (LinalgOp linalgOp)
Returns all the operands of linalgOp that are not views.
Asserts that these operands are value types to allow transformations like tiling to just use the values when cloning linalgOp.
Definition at line 89 of file Utils.cpp.
Referenced by cloneWithLoopRanges(), promoteSubViews(), and tileLinalgOpImpl().
getViewSizes()
template<typename ConcreteOp > SmallVector<Value, 8> mlir::linalg::getViewSizes (OpBuilder & builder, ConcreteOp linalgOp)
Returns the linearized list of all view dimensions in a linalgOp.
Applying the inverse, concatenated loopToOperandRangeMaps to this list allows the derivation of loop ranges for any linalgOp.
Definition at line 85 of file Utils.h.
References applyMapToValues(), and mlir::OpBuilder::create().
Referenced by getInputAndOutputIndices(), and tileLinalgOpImpl().
interchange()
LinalgOp mlir::linalg::interchange (LinalgOp op, ArrayRef< unsigned > interchangeVector)
Interchanges the iterator_types and iterator_maps dimensions of op.
This is an in-place transformation controlled by interchangeVector. An empty vector is interpreted as the identity permutation and the transformation returns early.
E.g. the permutation (i,j,k) -> (j,k,i) is expressed with interchangeVector = [1,2,0]. All values in interchangeVector must be integers, in the range 0..op.rank without duplications (i.e. [1,1,2] is an invalid permutation).
Definition at line 56 of file Interchange.cpp.
References applyPermutationToVector(), mlir::AffineMap::compose(), mlir::AffineMapAttr::get(), mlir::ArrayAttr::get(), mlir::getIndexingMapsAttrName(), mlir::getIteratorTypesAttrName(), mlir::AffineMap::getPermutationMap(), and mlir::inversePermutation().
Referenced by mlir::linalg::LinalgBaseInterchangePattern::matchAndRewrite().
interchangeGenericLinalgOpPrecondition()
LogicalResult mlir::linalg::interchangeGenericLinalgOpPrecondition (Operation * op, ArrayRef< unsigned > interchangeVector)
Emits a generic or indexed_generic operation with the indexing_maps and iterator_types permutated according to permutation.
Definition at line 35 of file Interchange.cpp.
References mlir::failure(), mlir::Operation::getContext(), mlir::AffineMap::getPermutationMap(), mlir::inversePermutation(), and mlir::success().
Referenced by mlir::linalg::LinalgBaseInterchangePattern::matchAndRewrite().
isFusableInto()
bool mlir::linalg::isFusableInto (const LinalgDependenceGraph & graph, LinalgOp consumer, Value consumedView, LinalgOp producer)
Checks whether fusing the specific producer of the consumedView is feasible.
This checks producer is the last write of consumedView and that no interleaved dependence would be violated (RAW, WAR or WAW).
Definition at line 263 of file Fusion.cpp.
References mlir::linalg::LinalgDependenceGraph::findCoveringDependences(), and isProducerLastWriteOfView().
Referenced by fuseProducerOfDep().
isProducerLastWriteOfView()
bool mlir::linalg::isProducerLastWriteOfView (const LinalgDependenceGraph & graph, LinalgOp consumer, Value consumedView, LinalgOp producer)
Checks whether the specific producer is the last write to exactly the whole consumedView.
This checks structural dominance, that the dependence is a RAW without any interleaved write to any piece of consumedView.
Definition at line 239 of file Fusion.cpp.
References mlir::linalg::LinalgDependenceGraph::findCoveringWrites(), and isStructurallyFusableProducer().
Referenced by isFusableInto().
linalgLowerOpToLoops()
template<typename LoopTy , typename ConcreteOp > Optional< LinalgLoops > mlir::linalg::linalgLowerOpToLoops (OpBuilder & builder, Operation * op)
Emits a loop nest of LoopTy with the proper body for op.
Emits a loop nest with the proper body for op.
Definition at line 745 of file Loops.cpp.
linalgOpToAffineLoops()
template<typename ConcreteOp > LogicalResult mlir::linalg::linalgOpToAffineLoops (OpBuilder & builder, Operation * op)
Emits a loop nest of affine.for with the proper body for op.
Definition at line 760 of file Loops.cpp.
References mlir::failure(), and mlir::success().
linalgOpToLoops()
template<typename ConcreteOp > LogicalResult mlir::linalg::linalgOpToLoops (OpBuilder & builder, Operation * op)
Emits a loop nest of loop.for with the proper body for op.
Definition at line 752 of file Loops.cpp.
References mlir::failure(), and mlir::success().
linalgOpToParallelLoops()
template<typename ConcreteOp > LogicalResult mlir::linalg::linalgOpToParallelLoops (OpBuilder & builder, Operation * op)
Emits a loop nest of loop.parallel with the proper body for op.
Definition at line 769 of file Loops.cpp.
References mlir::failure(), and mlir::success().
makeAffineDimExprs()
SmallVector< AffineExpr, 4 > mlir::linalg::makeAffineDimExprs (unsigned num, unsigned & startIdx, MLIRContext * context)
Returns num AffineDimExpr dimensions at positions [startIdx, startIdx + num) and increments startIdx to startIdx + num.
Definition at line 939 of file LinalgOps.cpp.
References mlir::getAffineDimExpr().
promoteSubViewOperands()
LinalgOp mlir::linalg::promoteSubViewOperands (OpBuilder & b, LinalgOp op, llvm::SetVector< Value > subViews, bool dynamicBuffers = false, int64_t alignment = 0, OperationFolder * folder = nullptr)
Promotes the subViews into a new buffer allocated at the insertion point b.
Promotion occurs in 3 steps:
Create a new buffer for a full tile (i.e. not clipped at the boundary).
Take a full view on the buffer and linalg.fill it with zeros (use float zero for now).
Take a partial slice of the full view in step 2. and copy into it. Infers statically sized buffers from subViews unless dynamicBuffers is true.
Returns a list of PromotionInfo which hold the promoted buffer and the full and partial views indexing into the buffer.
Referenced by mlir::linalg::LinalgBasePromotionPattern::matchAndRewrite(), promoteSubViews(), and promoteSubViews().
promoteSubViews()
SmallVector< PromotionInfo, 8 > mlir::linalg::promoteSubViews (OpBuilder & b, Location loc, ArrayRef< Value > subViews, bool dynamicBuffers = false, int64_t alignment = 0, OperationFolder * folder = nullptr)
Promotes the subViews into a new buffer allocated at the insertion point b.
For now, promotion occurs in 3 steps:
Create a new buffer for a full tile (i.e. not clipped at the boundary).
Take a full view on the buffer and linalg.fill it with zeros (use float zero for now).
Take a partial slice of the full view in step 2. and copy into it. Infers statically sized buffers from subViews unless dynamicBuffers is true.
Returns a list of PromotionInfo which hold the promoted buffer and the full and partial views indexing into the buffer.
Definition at line 140 of file Promotion.cpp.
References mlir::FloatAttr::get(), getAssumedNonViewOperands(), promoteFullTileBuffer(), promoteSubViewOperands(), and promoteSubViews().
promoteSubviewsLinalgOpPrecondition()
LogicalResult mlir::linalg::promoteSubviewsLinalgOpPrecondition (Operation * op, llvm::Optional< DenseSet< unsigned >> operandIndicesToPromote = None)
Promote std.subviews feeding linalg operations.
Definition at line 268 of file Promotion.cpp.
References mlir::detail::enumerate(), mlir::failure(), promoteSubViews(), and mlir::success().
Referenced by mlir::linalg::LinalgBasePromotionPattern::matchAndRewrite(), and mlir::linalg::LinalgLoweringPattern< OpTy >::matchAndRewrite().
tileLinalgOp() [1/2]
Optional< TiledLinalgOp > mlir::linalg::tileLinalgOp (OpBuilder & b, LinalgOp op, ArrayRef< Value > tileSizes, ArrayRef< unsigned > interchangeVector = {}, OperationFolder * folder = nullptr)
Performs standalone tiling of a single LinalgOp by tileSizes.
and permute the loop nest according to interchangeVector The permutation is expressed as a list of integers that specify the new ordering of the loop nest. The length of interchangeVector must be equal to the length of tileSizes. An empty vector is interpreted as the identity permutation and the transformation returns early.
When non-null, the optional pointer folder is used to call into the createAndFold builder method. If folder is null, the regular create method is called.
Returns a struct containing the tiled loops in the specified order and the cloned op if successful, llvm::None otherwise.
E.g. the permutation (i,j,k) -> (j,k,i) is expressed by interchangeVector = [1,2,0]. All values in interchangeVector must be integers, in the range 0..tileSizes.size() without duplications (i.e. [1,1,2] is an invalid permutation).
Definition at line 468 of file Tiling.cpp.
Referenced by mlir::linalg::LinalgBaseTilingPattern::matchAndRewrite().
tileLinalgOp() [2/2]
Optional< TiledLinalgOp > mlir::linalg::tileLinalgOp (OpBuilder & b, LinalgOp op, ArrayRef< int64_t > tileSizes, ArrayRef< unsigned > interchangeVector = {}, OperationFolder * folder = nullptr)
Performs standalone tiling of a single LinalgOp by constant tileSizes.
See tileLinalgOp(... ArrayRef<Value> tileSizes,) for more details
Definition at line 482 of file Tiling.cpp.
tileLinalgOpToParallelLoops() [1/2]
Optional< TiledLinalgOp > mlir::linalg::tileLinalgOpToParallelLoops (OpBuilder & b, LinalgOp op, ArrayRef< Value > tileSizes, ArrayRef< unsigned > interchangeVector = {}, OperationFolder * folder = nullptr)
Definition at line 475 of file Tiling.cpp.
Referenced by mlir::linalg::LinalgBaseTilingPattern::matchAndRewrite().
tileLinalgOpToParallelLoops() [2/2]
Optional< TiledLinalgOp > mlir::linalg::tileLinalgOpToParallelLoops (OpBuilder & b, LinalgOp op, ArrayRef< int64_t > tileSizes, ArrayRef< unsigned > interchangeVector = {}, OperationFolder * folder = nullptr)
Definition at line 489 of file Tiling.cpp.
vectorizeLinalgOp()
void mlir::linalg::vectorizeLinalgOp (OpBuilder & builder, Operation * op)
Emit a suitable vector form for a Linalg op with fully static shape.
Definition at line 97 of file Vectorization.cpp.
References DEBUG_TYPE, mlir::Operation::getLoc(), mlir::succeeded(), and vectorizeLinalgOpPrecondition().
Referenced by mlir::linalg::LinalgBaseVectorizationPattern::matchAndRewrite().
vectorizeLinalgOpPrecondition()
LogicalResult mlir::linalg::vectorizeLinalgOpPrecondition (Operation * op)
Rewrite a linalg.generic into a suitable vector.contraction op.
Definition at line 70 of file Vectorization.cpp.
References mlir::failure(), mlir::ShapedType::hasStaticShape(), mlir::isRowMajorMatmul(), and mlir::success().
Referenced by mlir::linalg::LinalgBaseVectorizationPattern::matchAndRewrite(), and vectorizeLinalgOp().
weightedPoolingInputIndex()
template<typename PoolingOp > SmallVector< AffineExpr, 4 > mlir::linalg::weightedPoolingInputIndex (PoolingOp op, ArrayRef< AffineExpr > outputDims, ArrayRef< AffineExpr > windowDims)
Builds the indexing expressions for a ConvOp/PoolingOp op.
Returns the vector of AffineMaps representing: stride[i] * outputDims[i] + dilation[i] * windowDims[i] - pad_low[i]
Definition at line 950 of file LinalgOps.cpp.