MLIR: lib/Parser/Parser.cpp File Reference
Parser.cpp File Reference
#include "mlir/Parser.h"
#include "Lexer.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/IntegerSet.h"
#include "mlir/IR/Location.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/Module.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/StandardTypes.h"
#include "mlir/IR/Verifier.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/ADT/bit.h"
#include "llvm/Support/PrettyStackTrace.h"
#include "llvm/Support/SMLoc.h"
#include "llvm/Support/SourceMgr.h"
#include <algorithm>
Enumerations
enum AffineLowPrecOp { LNoOp, Add, Sub }
Lower precedence ops (all at the same precedence level).
enum AffineHighPrecOp {
HNoOp, Mul, FloorDiv, CeilDiv,
Mod
}
Higher precedence ops - all at the same precedence level.
Functions
template<typename Symbol , typename SymbolAliasMap , typename CreateFn >
static Symbol parseExtendedSymbol (Parser &p, Token::Kind identifierTok, SymbolAliasMap &aliases, CreateFn &&createSymbol)
Parse an extended dialect symbol.
template<typename T , typename ParserFn >
static T parseSymbol (StringRef inputStr, MLIRContext *context, SymbolState &symbolState, ParserFn &&parserFn, size_t *numRead=nullptr)
Parses a symbol, of type 'T', and returns it if parsing was successful.
static std::string extractSymbolReference (Token tok)
Return the symbol reference referred to by the given token, that is known to be an -identifier.
static Optional< APFloat > buildHexadecimalFloatLiteral (Parser *p, FloatType type, uint64_t value)
Construct a float attribute bitwise equivalent to the integer literal.
static Optional< APInt > buildAttributeAPInt (Type type, bool isNegative, StringRef spelling)
Construct an APint from a parsed value, a known attribute type and sign.
static ParseResult parseElementAttrHexValues (Parser &parser, Token tok, std::string &result)
Parse elements values stored within a hex etring.
template<typename T , typename ParserFn >
static T parseSymbol (StringRef inputStr, MLIRContext *context, size_t &numRead, ParserFn &&parserFn)
Parses a symbol, of type 'T', and returns it if parsing was successful.
Enumeration Type Documentation
AffineHighPrecOp
enum AffineHighPrecOp
Higher precedence ops - all at the same precedence level.
HNoOp is false in the boolean sense.
Enumerator
HNoOp
Null value.
Mul
FloorDiv
CeilDiv
Mod
Definition at line 2630 of file Parser.cpp.
AffineLowPrecOp
enum AffineLowPrecOp
Lower precedence ops (all at the same precedence level).
LNoOp is false in the boolean sense.
Enumerator
LNoOp
Null value.
Add
Sub
Definition at line 2621 of file Parser.cpp.
Function Documentation
buildAttributeAPInt()
static Optional<APInt> buildAttributeAPInt (Type type, bool isNegative, StringRef spelling) static
Construct an APint from a parsed value, a known attribute type and sign.
Definition at line 1794 of file Parser.cpp.
References mlir::InFlightDiagnostic::attachNote(), buildHexadecimalFloatLiteral(), mlir::Type::dyn_cast(), mlir::emitError(), mlir::FloatAttr::get(), mlir::Builder::getIntegerAttr(), mlir::Builder::getIntegerType(), mlir::Type::getIntOrFloatBitWidth(), mlir::Token::getUInt64IntegerValue(), mlir::Type::isa(), mlir::Type::isIndex(), mlir::Type::isSignedInteger(), mlir::Type::isUnsignedInteger(), mlir::IndexType::kInternalStorageBitWidth, mlir::StandardTypes::None, and mlir::parseType().
Referenced by parseElementAttrHexValues().
buildHexadecimalFloatLiteral()
static Optional<APFloat> buildHexadecimalFloatLiteral (Parser * p, FloatType type, uint64_t value) static
Construct a float attribute bitwise equivalent to the integer literal.
Definition at line 1777 of file Parser.cpp.
References mlir::FloatType::getFloatSemantics(), mlir::FloatType::getWidth(), and mlir::StandardTypes::None.
Referenced by buildAttributeAPInt(), and parseElementAttrHexValues().
extractSymbolReference()
static std::string extractSymbolReference (Token tok) static
Return the symbol reference referred to by the given token, that is known to be an -identifier.
Definition at line 1490 of file Parser.cpp.
References mlir::emitError(), mlir::failed(), mlir::failure(), mlir::Identifier::get(), mlir::AffineMapAttr::get(), mlir::NoneType::get(), mlir::FloatAttr::get(), mlir::IntegerSetAttr::get(), mlir::StringAttr::get(), mlir::SymbolRefAttr::get(), mlir::TypeAttr::get(), mlir::Builder::getArrayAttr(), mlir::Builder::getBoolAttr(), mlir::OpaqueAttr::getChecked(), mlir::Builder::getDictionaryAttr(), mlir::Builder::getF64Type(), mlir::Builder::getIdentifier(), mlir::Token::getSpelling(), mlir::Token::getStringValue(), mlir::Builder::getSymbolRefAttr(), mlir::Attribute::getType(), mlir::Builder::getUnitAttr(), mlir::Token::is(), mlir::Type::isa(), mlir::parseAttribute(), mlir::parseType(), and mlir::success().
parseElementAttrHexValues()
static ParseResult parseElementAttrHexValues (Parser & parser, Token tok, std::string & result) static
Parse elements values stored within a hex etring.
On success, the values are stored into 'result'.
Definition at line 1891 of file Parser.cpp.
References buildAttributeAPInt(), buildHexadecimalFloatLiteral(), mlir::Type::cast(), mlir::Type::dyn_cast(), mlir::emitError(), mlir::failed(), mlir::failure(), mlir::Identifier::get(), mlir::CallSiteLoc::get(), mlir::FileLineColLoc::get(), mlir::FusedLoc::get(), mlir::NameLoc::get(), mlir::UnknownLoc::get(), mlir::RankedTensorType::get(), mlir::DenseElementsAttr::get(), mlir::DenseStringElementsAttr::get(), mlir::OpaqueElementsAttr::get(), mlir::SparseElementsAttr::get(), mlir::Builder::getContext(), mlir::ShapedType::getDimSize(), mlir::ShapedType::getElementType(), mlir::Token::getFloatingPointValue(), mlir::FloatType::getFloatSemantics(), mlir::DenseElementsAttr::getFromRawBuffer(), mlir::Builder::getIntegerType(), mlir::Token::getLoc(), mlir::ShapedType::getRank(), mlir::MLIRContext::getRegisteredDialect(), getShape(), mlir::ShapedType::getShape(), mlir::Token::getSpelling(), mlir::Token::getStringValue(), mlir::Token::getUInt64IntegerValue(), mlir::DenseElementsAttr::getValue(), mlir::Token::is(), mlir::Attribute::isa(), mlir::Type::isa(), mlir::Token::isAny(), mlir::Type::isInteger(), mlir::Type::isIntOrFloat(), mlir::Type::isIntOrIndex(), mlir::Type::isIntOrIndexOrFloat(), mlir::Type::isUnsignedInteger(), mlir::DenseElementsAttr::isValidRawBuffer(), mlir::parseAttribute(), mlir::parseType(), and mlir::success().
parseExtendedSymbol()
template<typename Symbol , typename SymbolAliasMap , typename CreateFn > static Symbol parseExtendedSymbol (Parser & p, Token::Kind identifierTok, SymbolAliasMap & aliases, CreateFn && createSymbol) static
Parse an extended dialect symbol.
Definition at line 766 of file Parser.cpp.
parseSymbol() [1/2]
template<typename T , typename ParserFn > static T parseSymbol (StringRef inputStr, MLIRContext * context, SymbolState & symbolState, ParserFn && parserFn, size_t * numRead = nullptr) static
Parses a symbol, of type 'T', and returns it if parsing was successful.
If parsing failed, nullptr is returned. The number of bytes read from the input string is returned in 'numRead'.
Definition at line 843 of file Parser.cpp.
References diag(), mlir::emitError(), mlir::failed(), mlir::failure(), mlir::Identifier::get(), mlir::ComplexType::get(), mlir::VectorType::get(), mlir::RankedTensorType::get(), mlir::UnrankedTensorType::get(), mlir::MemRefType::get(), mlir::UnrankedMemRefType::get(), mlir::TupleType::get(), mlir::Builder::getBF16Type(), mlir::IntegerType::getChecked(), mlir::OpaqueType::getChecked(), mlir::MemRefType::getDynamicStrideOrOffset(), mlir::Builder::getF16Type(), mlir::Builder::getF32Type(), mlir::Builder::getF64Type(), mlir::Builder::getFunctionType(), mlir::Builder::getIndexType(), mlir::Token::getLoc(), mlir::Builder::getNoneType(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumResults(), mlir::ShapedType::isDynamic(), mlir::Token::isNot(), mlir::VectorType::isValidElementType(), mlir::TensorType::isValidElementType(), mlir::IntegerType::kMaxWidth, mlir::makeStridedLinearLayoutMap(), mlir::StandardTypes::None, mlir::parseAttribute(), mlir::parseType(), mlir::IntegerType::Signed, mlir::IntegerType::Signless, mlir::success(), and mlir::IntegerType::Unsigned.
parseSymbol() [2/2]
template<typename T , typename ParserFn > static T parseSymbol (StringRef inputStr, MLIRContext * context, size_t & numRead, ParserFn && parserFn) static
Parses a symbol, of type 'T', and returns it if parsing was successful.
If parsing failed, nullptr is returned. The number of bytes read from the input string is returned in 'numRead'.
Definition at line 5144 of file Parser.cpp.
References mlir::Type::getContext(), mlir::parseAttribute(), and mlir::parseType().