MLIR: lib/Dialect/Linalg/Transforms/Promotion.cpp File Reference
Promotion.cpp File Reference
#include "PassDetail.h"
#include "mlir/Dialect/Affine/EDSC/Intrinsics.h"
#include "mlir/Dialect/Linalg/EDSC/FoldedIntrinsics.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/IR/LinalgTypes.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/LoopOps/LoopOps.h"
#include "mlir/Dialect/StandardOps/EDSC/Intrinsics.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineExprVisitor.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Transforms/FoldUtils.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/Support/CommandLine.h"
Macros
#define DEBUG_TYPE "linalg-promotion"
Typedefs
using folded_affine_min = FoldedValueBuilder< AffineMinOp >
using folded_linalg_range = FoldedValueBuilder< linalg::RangeOp >
using folded_std_dim = FoldedValueBuilder< DimOp >
using folded_std_subview = FoldedValueBuilder< SubViewOp >
using folded_std_view = FoldedValueBuilder< ViewOp >
Functions
static Value extractSmallestConstantBoundingSize (OpBuilder &b, Location loc, Value size)
If size comes from an AffineMinOp and one of the dimensions of AffineMin is a constant then return a new value set to the smallest such constant.
static Value allocBuffer (Type elementType, Value size, bool dynamicBuffers, OperationFolder *folder, int64_t alignment=0)
static PromotionInfo promoteFullTileBuffer (OpBuilder &b, Location loc, SubViewOp subView, bool dynamicBuffers, int64_t alignment, OperationFolder *folder)
static void promoteSubViews (FuncOp f, bool dynamicBuffers)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "linalg-promotion"
Definition at line 46 of file Promotion.cpp.
Typedef Documentation
folded_affine_min
using folded_affine_min = FoldedValueBuilder<AffineMinOp>
Definition at line 40 of file Promotion.cpp.
folded_linalg_range
using folded_linalg_range = FoldedValueBuilder<linalg::RangeOp>
Definition at line 41 of file Promotion.cpp.
folded_std_dim
using folded_std_dim = FoldedValueBuilder<DimOp>
Definition at line 42 of file Promotion.cpp.
folded_std_subview
using folded_std_subview = FoldedValueBuilder<SubViewOp>
Definition at line 43 of file Promotion.cpp.
folded_std_view
using folded_std_view = FoldedValueBuilder<ViewOp>
Definition at line 44 of file Promotion.cpp.
Function Documentation
allocBuffer()
static Value allocBuffer (Type elementType, Value size, bool dynamicBuffers, OperationFolder * folder, int64_t alignment = 0) static
Definition at line 68 of file Promotion.cpp.
References mlir::IntegerType::get(), mlir::IntegerAttr::get(), mlir::MemRefType::get(), mlir::Value::getContext(), mlir::Value::getDefiningOp(), and mlir::Type::getIntOrFloatBitWidth().
Referenced by promoteFullTileBuffer().
extractSmallestConstantBoundingSize()
static Value extractSmallestConstantBoundingSize (OpBuilder & b, Location loc, Value size) static
If size comes from an AffineMinOp and one of the dimensions of AffineMin is a constant then return a new value set to the smallest such constant.
Otherwise return size.
Definition at line 51 of file Promotion.cpp.
References mlir::OpBuilder::create(), and mlir::Value::getDefiningOp().
Referenced by promoteFullTileBuffer().
promoteFullTileBuffer()
static PromotionInfo promoteFullTileBuffer (OpBuilder & b, Location loc, SubViewOp subView, bool dynamicBuffers, int64_t alignment, OperationFolder * folder) static
Definition at line 103 of file Promotion.cpp.
References allocBuffer(), mlir::detail::enumerate(), extractSmallestConstantBoundingSize(), and mlir::MemRefType::get().
Referenced by mlir::linalg::promoteSubViews().
promoteSubViews()
static void promoteSubViews (FuncOp f, bool dynamicBuffers) static
Definition at line 244 of file Promotion.cpp.
References mlir::OpState::getContext(), mlir::linalg::promoteSubViewOperands(), and mlir::OpState::walk().
Referenced by mlir::linalg::promoteSubViews(), and mlir::linalg::promoteSubviewsLinalgOpPrecondition().