MLIR: lib/Dialect/Linalg/Transforms/Tiling.cpp File Reference
Tiling.cpp File Reference
#include "PassDetail.h"
#include "mlir/Dialect/Affine/EDSC/Intrinsics.h"
#include "mlir/Dialect/Linalg/EDSC/FoldedIntrinsics.h"
#include "mlir/Dialect/Linalg/IR/LinalgTypes.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/LoopOps/EDSC/Builders.h"
#include "mlir/Dialect/StandardOps/EDSC/Intrinsics.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineExprVisitor.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Transforms/FoldUtils.h"
#include "llvm/Support/CommandLine.h"
Macros
#define DEBUG_TYPE "linalg-tiling"
Typedefs
using folded_affine_min = FoldedValueBuilder< AffineMinOp >
using LoopIndexToRangeIndexMap = DenseMap< int, int >
Functions
static bool isZero (Value v)
static std::tuple< SmallVector< SubViewOp::Range, 4 >, LoopIndexToRangeIndexMap > makeTiledLoopRanges (OpBuilder &b, Location loc, AffineMap map, ArrayRef< Value > allViewSizes, ArrayRef< Value > allTileSizes, OperationFolder *folder)
static void transformIndexedGenericOpIndices (OpBuilder &b, LinalgOp op, SmallVectorImpl< Value > &ivs, const LoopIndexToRangeIndexMap &loopIndexToRangeIndex)
static bool isTiled (AffineExpr expr, ArrayRef< Value > tileSizes)
static bool isTiled (AffineMap map, ArrayRef< Value > tileSizes)
static SmallVector< Value, 4 > makeTiledViews (OpBuilder &b, Location loc, LinalgOp linalgOp, ArrayRef< Value > ivs, ArrayRef< Value > tileSizes, ArrayRef< Value > viewSizes, OperationFolder *folder)
template<typename LoopTy >
static Optional< TiledLinalgOp > tileLinalgOpImpl (OpBuilder &b, LinalgOp op, ArrayRef< Value > tileSizes, ArrayRef< unsigned > interchangeVector, OperationFolder *folder)
template<typename LoopTy >
static Optional< TiledLinalgOp > tileLinalgOpImpl (OpBuilder &b, LinalgOp op, ArrayRef< int64_t > tileSizes, ArrayRef< unsigned > interchangeVector, OperationFolder *folder)
template<typename LoopTy >
static void tileLinalgOps (FuncOp f, ArrayRef< int64_t > tileSizes)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "linalg-tiling"
Definition at line 38 of file Tiling.cpp.
Typedef Documentation
folded_affine_min
using folded_affine_min = FoldedValueBuilder<AffineMinOp>
Definition at line 36 of file Tiling.cpp.
LoopIndexToRangeIndexMap
using LoopIndexToRangeIndexMap = DenseMap<int, int>
Definition at line 45 of file Tiling.cpp.
Function Documentation
isTiled() [1/2]
static bool isTiled (AffineExpr expr, ArrayRef< Value > tileSizes) static
Definition at line 206 of file Tiling.cpp.
Referenced by isTiled(), makeTiledLoopRanges(), and makeTiledViews().
isTiled() [2/2]
static bool isTiled (AffineMap map, ArrayRef< Value > tileSizes) static
Definition at line 216 of file Tiling.cpp.
References mlir::AffineMap::getNumResults(), mlir::AffineMap::getResult(), and isTiled().
isZero()
static bool isZero (Value v) static
Definition at line 40 of file Tiling.cpp.
References mlir::Value::getDefiningOp().
Referenced by makeTiledLoopRanges(), makeTiledViews(), and tileLinalgOpImpl().
makeTiledLoopRanges()
static std::tuple<SmallVector<SubViewOp::Range, 4>, LoopIndexToRangeIndexMap> makeTiledLoopRanges (OpBuilder & b, Location loc, AffineMap map, ArrayRef< Value > allViewSizes, ArrayRef< Value > allTileSizes, OperationFolder * folder) static
Definition at line 57 of file Tiling.cpp.
References mlir::linalg::applyMapToValues(), mlir::AffineExpr::cast(), mlir::AffineExpr::getKind(), mlir::AffineBinaryOpExpr::getLHS(), mlir::AffineMap::getNumResults(), mlir::AffineDimExpr::getPosition(), mlir::AffineBinaryOpExpr::getRHS(), isTiled(), isZero(), mlir::Mul, and mlir::linalg::Range.
Referenced by tileLinalgOpImpl().
makeTiledViews()
static SmallVector<Value, 4> makeTiledViews (OpBuilder & b, Location loc, LinalgOp linalgOp, ArrayRef< Value > ivs, ArrayRef< Value > tileSizes, ArrayRef< Value > viewSizes, OperationFolder * folder) static
Definition at line 226 of file Tiling.cpp.
References mlir::linalg::applyMapToValues(), mlir::Type::cast(), mlir::OpBuilder::create(), mlir::Operation::erase(), mlir::AffineMap::get(), mlir::getAffineDimExpr(), mlir::Builder::getContext(), mlir::Value::getDefiningOp(), mlir::Builder::getIndexType(), mlir::Value::getType(), mlir::ShapedType::isDynamic(), isTiled(), isZero(), and mlir::Value::use_empty().
Referenced by tileLinalgOpImpl().
tileLinalgOpImpl() [1/2]
template<typename LoopTy > static Optional<TiledLinalgOp> tileLinalgOpImpl (OpBuilder & b, LinalgOp op, ArrayRef< Value > tileSizes, ArrayRef< unsigned > interchangeVector, OperationFolder * folder) static
Definition at line 324 of file Tiling.cpp.
References mlir::linalg::applyMapToValues(), mlir::linalg::applyPermutationToVector(), mlir::concatAffineMaps(), mlir::linalg::getAssumedNonViewOperands(), mlir::edsc::ScopedContext::getBuilderRef(), mlir::edsc::ScopedContext::getContext(), mlir::edsc::ScopedContext::getLocation(), mlir::AffineMap::getMultiDimIdentityMap(), mlir::BlockArgument::getOwner(), mlir::Block::getParentOp(), mlir::AffineMap::getPermutationMap(), mlir::AffineMapAttr::getValue(), mlir::linalg::getViewSizes(), mlir::inversePermutation(), isZero(), makeTiledLoopRanges(), makeTiledViews(), mlir::StandardTypes::None, mlir::OpBuilder::setInsertionPoint(), and transformIndexedGenericOpIndices().
tileLinalgOpImpl() [2/2]
template<typename LoopTy > static Optional<TiledLinalgOp> tileLinalgOpImpl (OpBuilder & b, LinalgOp op, ArrayRef< int64_t > tileSizes, ArrayRef< unsigned > interchangeVector, OperationFolder * folder) static
Definition at line 422 of file Tiling.cpp.
References mlir::StandardTypes::None, and mlir::OpBuilder::setInsertionPoint().
tileLinalgOps()
template<typename LoopTy > static void tileLinalgOps (FuncOp f, ArrayRef< int64_t > tileSizes) static
Definition at line 497 of file Tiling.cpp.
References mlir::OpState::getContext(), mlir::isOpTriviallyDead(), and mlir::OpState::walk().
transformIndexedGenericOpIndices()
static void transformIndexedGenericOpIndices (OpBuilder & b, LinalgOp op, SmallVectorImpl< Value > & ivs, const LoopIndexToRangeIndexMap & loopIndexToRangeIndex) static
Definition at line 166 of file Tiling.cpp.
References mlir::OpBuilder::create(), mlir::Value::getDefiningOp(), mlir::Value::getUses(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by tileLinalgOpImpl().